--- Configuration for the LVS Compatibility Module.
-- @configuration LVS
--- This table defines the default settings for the LVS Module.
-- @realm shared
-- @table Configuration
-- @field DamageInCars Whether or not you take damage while in cars? | **boolean**
