Core:OnContextMenuOpen()
Core:OnContextMenuClose()
Core:LoadLiliaFonts(font, genericFont)
Core:CreateLoadingScreen()
Core:ShouldCreateLoadingScreen()
Core:InitializedConfig()
Core:CharacterListLoaded()
Core:InitPostEntity()
Core:CalcView(client, origin, angles, fov)
Core:HUDPaintBackground()
Core:ShouldDrawEntityInfo(entity)
Core:PlayerBindPress(client, bind, pressed)
Core:ItemShowEntityMenu(entity)
Core:SetupQuickMenu(menu)
Core:DrawLiliaModelView(panel, ent)
Core:ScreenResolutionChanged(oldW, oldH)
Core:LiliaLoaded()
Core:PlayerNoClip(client)
Core:TranslateActivity(client, act)
Core:DoAnimationEvent(client, event, data)
Core:EntityEmitSound(data)
Core:HandlePlayerLanding(client, velocity, wasOnGround)
Core:CalcMainActivity(client, velocity)
Core:OnCharVarChanged(char, varName, oldVar, newVar)
Core:GetDefaultCharName(client, faction)
Core:GetDefaultCharDesc(client, faction)
Core:CanPlayerUseChar(client, char)
Core:CheckFactionLimitReached(faction, character, client)
Core:CanProperty(client, property, entity)
Core:PhysgunPickup(client, entity)
Core:Move(client, moveData)
Core:CanItemBeTransfered(itemObject, curInv, inventory)
Core:SetupBotCharacter(client)
Core:SetupBotInventory(client, character)
Core:PlayerInitialSpawn(client)
Core:PlayerUse(client, entity)
Core:KeyPress(client, key)
Core:KeyRelease(client, key)
Core:CanPlayerDropItem(client, item)
Core:CanPlayerInteractItem(client, action, item)
Core:CanPlayerTakeItem(client, item)
Core:PlayerShouldTakeDamage(client, attacker)
Core:EntityTakeDamage(entity, dmgInfo)
Core:PrePlayerLoadedChar(client, character, lastChar)
Core:PlayerLoadedChar(client, character, lastChar)
Core:CharacterLoaded(id)
Core:PlayerSay(client, message)
Core:PlayerSpawn(client)
Core:PlayerSpawnNPC(client, npcType, weapon)
Core:PlayerSpawnSWEP(client, weapon, info)
Core:PlayerSpawnProp(client)
Core:PlayerSpawnRagdoll(client)
Core:PlayerSpawnVehicle(client, model, name, data)
Core:PlayerLoadout(client)
Core:PostPlayerLoadout(client)
Core:PlayerDeath(client, inflictor, attacker)
Core:PlayerHurt(client, attacker, health, damage)
Core:PlayerDeathThink(client)
Core:PlayerDisconnected(client)
Core:PlayerAuthed(client, steamID, uniqueID)
Core:InitPostEntity()
Core:ShutDown()
Core:PlayerDeathSound()
Core:InitializedSchema()
Core:PlayerCanHearPlayersVoice(listener, speaker)
Core:OnPhysgunFreeze(weapon, physObj, entity, client)
Core:CanPlayerSuicide(client)
Core:AllowPlayerPickup(client, entity)
Core:PreCleanupMap()
Core:PostCleanupMap()
Core:CharacterPreSave(character)
Core:OnServerLog(client, logType, ...)
Core:GetPreferredCarryAngles(entity)
Core:InitializedPlugins()
Core:CreateDefaultInventory(character)
Core:LiliaTablesLoaded()
Core:PluginShouldLoad(plugin)
Core:GetSalaryInterval(client, faction)
Core:CreateSalaryTimer(client)
Core:GetGameDescription()
Core:OnPlayerJoinClass(client, class, oldClass)
Core:OnPickupMoney(client, moneyEntity)
Core:PlayerAuthed(client, steamID, uniqueID)
Core:SetupDatabase()
Core:OnMySQLOOConnected()
Core:RegisterPreparedStatements()
Core:Initialize()
Core:OnReloaded()