util.AddNetworkString("liaRequestLogs")
util.AddNetworkString("liaDrawLogs")
util.AddNetworkString("liaRequestLogs")
net.Receive("liaRequestLogs", function(len, client)
    local selectedDate = net.ReadString()
    local logs = LoggerCore:ReadLogsFromFile(selectedDate)
    net.Start("liaDrawLogs")
    net.WriteTable(logs)
    net.Send(client)
end)