--------------------------------------------------------------------------------------------------------
local PANEL = {}
--------------------------------------------------------------------------------------------------------
function PANEL:Init()
    self:SetTitle(L("thirdpersonConfig"))
    self:SetSize(300, 140)
    self:Center()
    self:MakePopup()
    self.list = self:Add("DPanel")
    self.list:Dock(FILL)
    self.list:DockMargin(0, 0, 0, 0)
    local cfgHeight = self.list:Add("DNumSlider")
    cfgHeight:Dock(TOP)
    cfgHeight:SetText("Height")
    cfgHeight:SetMin(0)
    cfgHeight:SetMax(30)
    cfgHeight:SetDecimals(0)
    cfgHeight:SetConVar("lia_tp_vertical")
    cfgHeight:DockMargin(10, 0, 0, 5)
    local cfgHorizontal = self.list:Add("DNumSlider")
    cfgHorizontal:Dock(TOP)
    cfgHorizontal:SetText("Horizontal")
    cfgHorizontal:SetMin(-30)
    cfgHorizontal:SetMax(30)
    cfgHorizontal:SetDecimals(0)
    cfgHorizontal:SetConVar("lia_tp_horizontal")
    cfgHorizontal:DockMargin(10, 0, 0, 5)
    local cfgDistance = self.list:Add("DNumSlider")
    cfgDistance:Dock(TOP)
    cfgDistance:SetText("Distance")
    cfgDistance:SetMin(0)
    cfgDistance:SetMax(100)
    cfgDistance:SetDecimals(0)
    cfgDistance:SetConVar("lia_tp_distance")
    cfgDistance:DockMargin(10, 0, 0, 5)
end

--------------------------------------------------------------------------------------------------------
vgui.Register("liaTPConfig", PANEL, "DFrame")
--------------------------------------------------------------------------------------------------------