--- Configuration for MainMenu Module.
-- @configuration MainMenu

--- This table defines the default settings for the MainMenu Module.
-- @realm shared
-- @table Configuration
-- @field MusicVolume Set Music Volume on Main Menu | **number**
-- @field Music Set Main Menu Background Music | **string**
-- @field BackgroundURL Set Background Image | **string**
-- @field CharMenuBGInputDisabled Disable Background Input during Main Menu Lookup | **boolean**
-- @field CanSelectBodygroups Enable or disable selection of bodygroups in the character menu | **boolean**
-- @field CanSelectSkins Enable or disable selection of skins in the character menu | **boolean**
-- @field KickOnEnteringMainMenu Set Music Volume on Main Menu | **boolean**