--- Configuration for the MainMenu Module.
-- @configuration MainMenu

--- This table defines the default settings for the MainMenu Module.
-- @realm shared
-- @table Configuration
-- @field MusicVolume The volume level for the main menu music | **number**
-- @field Music The file path or URL for the main menu background music | **string**
-- @field BackgroundURL The URL or file path for the main menu background image | **string**
-- @field CenterLogo The file path or URL for the logo displayed at the center of the screen | **string**
-- @field ButtonLogo The file path or URL for the logo displayed on the button | **string**
-- @field ButtonURL The URL opened when the button with ButtonLogo is clicked | **string**
-- @field CharMenuBGInputDisabled Whether background input is disabled during character menu use | **boolean**
-- @field CanSelectBodygroups Whether players can select bodygroups in the character menu | **boolean**
-- @field CanSelectSkins Whether players can select skins in the character menu | **boolean**
-- @field KickOnEnteringMainMenu Whether players are kicked upon entering the main menu | **boolean**