--- Configuration for MainMenu Module.
-- @configurationmodule MainMenu

--- This table defines the default settings for the MainMenu Module.
-- @realm shared
-- @table Configuration
-- @field MusicVolume Set Music Volume on Main Menu | **number**
-- @field Music Set Main Menu Background Music | **string**
-- @field LogoURL Set Main Menu Logo | **string**
-- @field BackgroundURL Set Background Image URL (if applicable) | **string**
-- @field BackgroundIsYoutubeVideo Set If Background Screen is a YT video | **bool**
-- @field CharMenuBGInputDisabled Disable Background Input during Main Menu Lookup | **bool**
-- @field CharCreationTransparentBackground Set Transparent Background during Character Creation | **bool**
