--- Configuration for Spawns Module.
-- @config Spawns

--- This table defines the default settings for the Spawns Module.
-- @realm shared
-- @table Configuration
-- @field LoseWeapononDeathNPC Determine if weapons are lost on death by NPCs | **bool**
-- @field LoseWeapononDeathHuman Determine if weapons are lost on death by Humans | **bool**
-- @field LoseWeapononDeathWorld Determine if weapons are lost on death by World | **bool**
-- @field WhitelistedSteamID64 Enable or disable the death information popup | **bool**
-- @field StaffHasGodMode Whether or not Staff On Duty has God Mode | **bool**