--- Configuration for the Spawns Module.
-- @configuration Spawns

--- This table defines the default settings for the Spawns Module.
-- @realm shared
-- @table Configuration
-- @field LoseDropItemsonDeathNPC Determine if weapons are lost on death by NPCs | **boolean**
-- @field LoseDropItemsonDeathHuman Determine if weapons are lost on death by Humans | **boolean**
-- @field LoseDropItemsonDeathWorld Determine if weapons are lost on death by World | **boolean**
-- @field WhitelistedSteamID64 Enable or disable the death information popup | **boolean**
-- @field StaffHasGodMode Whether or not Staff On Duty has God Mode | **boolean**
