exclude_files = {
    "lilia/modules/frameworkui/mainmenu/*.lua",
    "lilia/modules/utilities/logging/definitions/logs.lua",
    "lilia/libraries/thirdparty/**/*.lua",
    "lilia/libraries/logger/**/*.lua",
    "lilia/libraries/database/**/*.lua",
    "lilia/libraries/inventory/**/*.lua",
    "lilia/libraries/items/**/*.lua",
    "lilia/libraries/util/*.lua",
    "development/**",
    "lilia/*.png",
    "lilia/*.txt",
    "lilia/docs/*.lua",
    "lilia/docs/**/*.lua",
}