MODULE.CustomChatSound = ""
MODULE.ChatColor = Color(255, 239, 150)
MODULE.ChatRange = 280
MODULE.ChatShowTime = false
MODULE.OOCLimit = 150
MODULE.ChatListenColor = Color(168, 240, 170)
MODULE.OOCDelay = 10
MODULE.OOCDelayAdmin = false
MODULE.LOOCDelayAdmin = false
MODULE.LOOCDelay = 6
MODULE.ChatSizeDiff = false
