MODULE.name = "Third Person"
MODULE.author = "76561198312513285"
MODULE.discord = "@liliaplayer"
MODULE.desc = "Adds Tweakable Third Person"
MODULE.version = "Stock"
MODULE.identifier = "ThirdPersonCore"