local HackCommands = {
    ["aimkey"] = true,
    ["+hera_aim"] = true,
    ["boom"] = true,
    ["-hera_aim"] = true,
    ["executer"] = true,
    ["+hera_speed"] = true,
    ["-hera_speed"] = true,
    ["+hera_menu"] = true,
    ["-hera_menu"] = true,
    ["lix_lesp_rotate3"] = true,
    ["lix_lesp_rotate"] = true,
    ["R8_Exploit"] = true,
    ["R8_Menu"] = true,
    ["ace_menu"] = true,
    ["bd_menu"] = true,
    ["bd_quickfire"] = true,
    ["bc_unload"] = true,
    ["sv_add1"] = true,
    ["sv_run1"] = true,
    ["exploit"] = true,
    ["print_server_cfg"] = true,
    ["print_file"] = true,
    ["dump_remote_lua2"] = true,
    ["print_file_listing_load"] = true,
    ["sv_printdirfiles"] = true,
    ["sv_printdir"] = true,
    ["****_admins"] = true,
    ["aah_setupspeedhack"] = true,
    ["_timescale"] = true,
    ["+enabled"] = true,
    ["+triggerbot"] = true,
    ["inc_g"] = true,
    ["Smelly_Print_IPs"] = true,
    ["Smelly_Clear_IPs"] = true,
    ["+autofire"] = true,
    ["spinlol"] = true,
    ["pp_pixelrender"] = true,
    ["startspam"] = true,
    ["stopspam"] = true,
    ["+makesound"] = true,
    ["makesound"] = true,
    ["+pk"] = true,
    ["ThrowMagneto"] = true,
    ["kon_chatspam"] = true,
    ["kon_stopspam"] = true,
    ["RLua"] = true,
    ["Orgflashstyle1"] = true,
    ["Orgflashstyle2"] = true,
    ["se_add"] = true,
    ["mh_unlock"] = true,
    ["mh_toggleflag"] = true,
    ["mh_keypad"] = true,
    ["mh_open"] = true,
    ["mh_turn180"] = true,
    ["mh_esp_rehook"] = true,
    ["mh_owners"] = true,
    ["+qq_aimbot_enabled"] = true,
    ["qq_menu"] = true,
    ["+qq_nospread_triggerbot"] = true,
    ["+qq_speedhack_speed"] = true,
    ["go_unconnected"] = true,
    ["+nou"] = true,
    ["metalslave_aimbot_reload"] = true,
    ["metalslave_aimbot_toggle"] = true,
    ["metalslave_aimbot_menu"] = true,
    ["metalslave_chams_reload"] = true,
    ["cf_aim_toggle"] = true,
    ["+cf_bunnyhop"] = true,
    ["CrashTheServer"] = true,
    ["UltraCrashTheServer"] = true,
    ["+cal_menu"] = true,
    ["+cal_aim"] = true,
    ["Isis_Menu_Reload"] = true,
    ["+Isis_Menu"] = true,
    ["+kilos_aim"] = true,
    ["Isis_InteractC4"] = true,
    ["+Isis_Aim"] = true,
    ["Isis_Spin"] = true,
    ["+Isis_Speed"] = true,
    ["cf_freeze"] = true,
    ["cf_menu"] = true,
    ["+cf_aim"] = true,
    ["+cf_speed"] = true,
    ["+DragonBot_Aim"] = true,
    ["DragonBot_menu"] = true,
    ["sh_luarun"] = true,
    ["2a1f3e4r5678j9r9w8j7d54k6r2a84"] = true,
    ["falco_runlooah"] = true,
    ["falco_openlooah"] = true,
    ["falco_rotate1"] = true,
    ["falco_rotate2"] = true,
    ["frotate"] = true,
    ["+falco_makesound"] = true,
    ["falco_makesound"] = true,
    ["+hermes_aim"] = true,
    ["_PoKi_menu_reload"] = true,
    ["spamjeeps"] = true,
    ["spamchair"] = true,
    ["exploits_open"] = true,
    ["falco_hotkey"] = true,
    ["falco_hotkeyList"] = true,
    ["+cb_aim"] = true,
    ["vlua_run"] = true,
    ["sh_print_traitors"] = true,
    ["+sh_triggerbot"] = true,
    ["sh_runscripts"] = true,
    ["sh_togglemenu"] = true,
    ["gen_aim"] = true,
    ["gen_autoshoot"] = true,
    ["gen_speed"] = true,
    ["+gen_bhop"] = true,
    ["+gen_aim"] = true,
    ["+gen_speed"] = true,
    ["Ares_ForceImpulse"] = true,
    ["Ares_Menu_ESP"] = true,
    ["Ares_Menu_Misc"] = true,
    ["Ares_Menu_AimBot"] = true,
    ["+Ares_Pointer"] = true,
    ["+Ares_SlowNikes"] = true,
    ["+Ares_Aim"] = true,
    ["+Ares_Nikes"] = true,
    ["+Ares_PropKill"] = true,
    ["Ares_Print_IPs"] = true,
    ["mint_toggle"] = true,
    ["phage_menu"] = true,
    ["mfsp_menu"] = true,
    ["+Hera_Menu"] = true,
    ["+asp_antidof"] = true,
    ["+rape"] = true,
    ["+iliek2rape"] = true,
    ["togglerape"] = true,
    ["aimbot_unload"] = true,
    ["+vh_speed"] = true,
    ["+vh_menu"] = true,
    ["gmhax_module_menu"] = true,
    ["gmhax_menu"] = true,
    ["gmhax_lua_view"] = true,
    ["+fap_speed"] = true,
    ["Defqon"] = true,
    ["yb_menu"] = true,
    ["norecoil"] = true,
    ["+yb_menu"] = true,
    ["+ab_aim"] = true,
    ["+spedd"] = true,
    ["int_speedamount"] = true,
    ["int_runlua"] = true,
    ["+chiefeh"] = true,
    ["_SG.ToggleBypass"] = true,
    ["_SG.ToggleSE"] = true,
    ["lua_run_override"] = true,
    ["micspamToggle"] = true,
    ["bk_menu"] = true,
    ["+bk_attack"] = true,
    ["+speedhack"] = true,
    ["bktb_toggle"] = true,
    ["bktb_on"] = true,
    ["bktb_off"] = true,
    ["+bktb"] = true,
    ["ForceCVar"] = true,
    ["runfile"] = true,
    ["+bk_forward"] = true,
    ["+bk_back"] = true,
    ["+bk_left"] = true,
    ["+bk_right"] = true,
    ["+aimbot"] = true,
    ["int_menu"] = true,
    ["+qq_noob2"] = true,
    ["+turbojordans"] = true,
    ["+qq_noob"] = true,
    ["th_menu"] = true,
    ["th_aimbot_on"] = true,
    ["+ph_speed"] = true,
    ["+ph_speedhack"] = true,
    ["+ph_aim"] = true,
    ["ph_aimhack"] = true,
    ["+ph_aimhack"] = true,
    ["ph_hackmenu"] = true,
    ["+Exmenu"] = true,
    ["+mechgear_shot"] = true,
    ["+wurst_silent"] = true,
    ["+wurst_getpos"] = true,
    ["+angel_menu"] = true,
    ["printips"] = true,
    ["+orgmenu"] = true,
    ["+BT"] = true,
    ["+woG"] = true,
    ["+cherry_menu"] = true,
    ["+cherry_aim"] = true,
    ["ProcessCommandBait"] = true,
    ["omen_spin"] = true,
    ["+propthrow"] = true,
    ["+scriptenforcer_menu"] = true,
    ["+comtarg"] = true,
    ["bs_hooks"] = true,
    ["+bh_menu"] = true,
    ["hake_menu"] = true,
    ["asp_rotate"] = true,
    ["asp_menu"] = true,
    ["+hake_aim"] = true,
    ["fls_menu"] = true,
    ["sh_alive"] = true,
    ["bs_detector"] = true,
    ["bs_doeffect"] = true,
    ["gf_admin"] = true,
    ["+uberslow"] = true,
    ["seb_openscript"] = true,
    ["bs_menu"] = true,
    ["+bs_getpos"] = true,
    ["odius_zoom"] = true,
    ["iHack_FullBright"] = true,
    ["+ihack_speedhack"] = true,
    ["ihack_speedhack"] = true,
    ["FCvar"] = true,
    ["+ihack_aimbot"] = true,
    ["ihack_menu"] = true,
    ["ihack_lua_scriptrun"] = true,
    ["ihack_lua_stringrun"] = true,
    ["lua_crypt"] = true,
    ["spinhack"] = true,
    ["at_autoaim_on"] = true,
    ["at_autoaim_off"] = true,
    ["+speed_hack"] = true,
    ["AddSpeed"] = true,
    ["_botjump"] = true,
    ["_botvelocity"] = true,
    ["+speedhake"] = true,
    ["cub_aim_toggle"] = true,
    ["cubHack"] = true,
    ["cubHackLaser"] = true,
    ["gen_run"] = true,
    ["gen_lua"] = true,
    ["+Coma_Pointer"] = true,
    ["Coma_Menu_AimBot"] = true,
    ["Coma_Menu_Misc"] = true,
    ["Coma_ForceImpulse"] = true,
    ["+Coma_SlowNikes"] = true,
    ["+Coma_Nikes"] = true,
    ["+Coma_PropKill"] = true,
    ["AC_toggle"] = true,
    ["AC_menu"] = true,
    ["AC_Misc_NameSteal"] = true,
    ["+AC"] = true,
    ["+AC_Speed"] = true,
    ["+SB_Aim"] = true,
    ["SB_Misc_Flood"] = true,
    ["SB_Misc_Crash"] = true,
    ["+SB_Speed"] = true,
    ["SB_Done"] = true,
    ["+sbot_aimbot"] = true,
    ["+Demibot_aim"] = true,
    ["fls_joinspam"] = true,
    ["fls_spamtimer"] = true,
    ["+coma_aim"] = true,
    ["coma_aim"] = true,
    ["coma_menu"] = true,
    ["+coma_menu"] = true,
    ["+exie_aim"] = true,
    ["+exie_speed"] = true,
    ["+exie_menu"] = true,
    ["exie_menu"] = true,
    ["Menu_H4x"] = true,
    ["fb_fov"] = true,
    ["fb_runscript"] = true,
    ["+fb"] = true,
    ["fb_load"] = true,
    ["omen_reload"] = true,
    ["omen_menu"] = true,
    ["+omen_aim"] = true,
    ["venus_menu"] = true,
    ["+venus_menu"] = true,
    ["Music_troll"] = true,
    ["Defqon_noclip"] = true,
    ["exploit_menu"] = true,
    ["*****"] = true,
    ["+omen_speed"] = true,
    ["+zaim"] = true,
    ["Obelus_Update"] = true,
    ["Obelus_Menu"] = true,
    ["+Obelus_Menu"] = true,
    ["+Obelus_Aim"] = true,
    ["Obelus_Aim"] = true,
    ["+Obelus_Speed"] = true,
    ["bs_force_load"] = true,
    ["lua_logo_reload"] = true,
    ["lua_run_quick"] = true,
    ["bs_reload"] = true,
    ["bs_unload"] = true,
    ["bs_inject"] = true,
    ["+bs_getview"] = true,
    ["odius_menu"] = true,
    ["+odius_aim"] = true,
    ["+odius_pkmode"] = true,
    ["fl_fillhp"] = true,
    ["+sp33d"] = true,
    ["+b_aim"] = true,
    ["server_command"] = true,
    ["toggle_target"] = true,
    ["target_menu"] = true,
    ["+aim"] = true,
    ["anthrax_banadmins"] = true,
    ["anthrax_demoteadmins"] = true,
    ["lol_rcon"] = true,
    ["+follow_aim"] = true,
    ["cs_lua"] = true,
    ["anthrax_filemenu"] = true,
    ["+anthrax_floodserver"] = true,
    ["getrcon"] = true,
    ["exploit_admin"] = true,
    ["exploit_bans"] = true,
    ["exploit_cfg"] = true,
    ["exploit_rcon"] = true,
    ["+fls_joinspam"] = true,
    ["fls_execlua"] = true,
    ["fls_loadlua"] = true,
    ["fls_weightcrash_setup"] = true,
    ["lethal_rotate"] = true,
    ["lethal_menu"] = true,
    ["lix_lesp_reload"] = true,
    ["join_stopspam"] = true,
    ["fls_rotate"] = true,
    ["lix_lesp_rotate1"] = true,
    ["lix_lesp_rotate2"] = true,
    ["fuck_admins"] = true,
    ["ox_hacexploit"] = true,
    ["trowmagneto"] = true,
    ["+qq_menu"] = true,
    ["aah_renamevar"] = true,
    ["aah_renamecmd"] = true,
    ["aah_updatelogsettings"] = true,
    ["aah_reload"] = true,
    ["aah_login"] = true,
    ["qq_aimbot_quick_shot"] = true,
    ["cf_menu_toggle"] = true,
    ["Ares_Clear_IPs"] = true,
    ["+MAim"] = true,
    ["ms_pato"] = true,
    ["+MSpeed"] = true,
    ["ms_sv_cheats"] = true,
    ["+MPause"] = true,
    ["+zumg"] = true,
    ["_fap_reload_menu"] = true,
    ["ThermHack_ToggleMenu"] = true,
    ["cub_toggle"] = true,
    ["hera_convar_get"] = true,
    ["hera_convar_set"] = true,
    ["hera_include"] = true,
    ["hera_runstring"] = true,
    ["Monster_Menu"] = true,
    ["x_reload"] = true,
    ["x_menu"] = true,
    ["+fox_aim"] = true,
    ["+hax_rapidfire"] = true,
    ["+Hax_aimbot"] = true,
    ["+Hax_Menu"] = true,
    ["+Hax_Zoom"] = true,
    ["+TB_Bhop"] = true,
    ["TB_Console"] = true,
    ["+ATMenu"] = true,
    ["+AimAssist"] = true,
    ["+AimBHOP"] = true,
    ["ReloadAA"] = true,
    ["h_runscript"] = true,
    ["gDaap_openscript"] = true,
    ["h_openscript"] = true,
    ["h_firewall"] = true,
    ["h_gtower_debug"] = true,
    ["h_bo_thirdperson"] = true,
    ["h_helxa_encrypt"] = true,
    ["h_helxa_decrypt"] = true,
    ["bypass_se"] = true,
    ["+hax_admin"] = true,
    ["Neon_LoadMenu"] = true,
    ["+Neon_Aim"] = true,
    ["+Neon_SpeedHack"] = true,
    ["+Neon_PropKill"] = true,
    ["Neon_SayTraitors"] = true,
    ["Neon_ForceCheats"] = true,
    ["+neon_menu"] = true,
    ["sb_toggle"] = true,
    ["sh_menu"] = true,
    ["asp_reload"] = true,
    ["+sh_bhop"] = true,
    ["asp_uploaddupe"] = true,
    ["+li_bhop"] = true,
    ["hake_load"] = true,
    ["SE_ByPass"] = true,
    ["se_on"] = true,
    ["+Aim"] = true,
    ["SpamTime"] = true,
    ["SethHack_panic"] = true,
    ["SethHack_lua_run"] = true,
    ["SethHack_lua_openscript"] = true,
    ["+SethHackToggle"] = true,
    ["+SethHack_Menu"] = true,
    ["deathrun_qq"] = true,
    ["+SethHack_Speed"] = true,
    ["SethHack_ff_toggle"] = true,
    ["SethHack_wallhack_wire"] = true,
    ["SethHack_wallhack_player"] = true,
    ["SethHack_Clear_All"] = true,
    ["SethHackToggle"] = true,
    ["SethHack_triggerbot_toggle"] = true,
    ["SethHack_AddNPCfriend"] = true,
    ["SpamMenu"] = true,
    ["Inkbot_Crack"] = true,
    ["Ink_LoadMenu"] = true,
    ["+Propkill"] = true,
    ["+int_aimbot"] = true,
    ["+Ink_Aim"] = true,
    ["Ink_menu"] = true,
    ["ihpublicaimbot_reload"] = true,
    ["ihpublicaimbot_toggle"] = true,
    ["+ihaimbot"] = true,
    ["ihpublicaimbot_menu"] = true,
    ["lagon"] = true,
    ["lagoff"] = true,
    ["fap_aimbot_toggle"] = true,
    ["+Nis_Menu"] = true,
    ["pb_aim_trigger"] = true,
    ["pb_load"] = true,
    ["+TB_Aim"] = true,
    ["+TB_Menu"] = true,
    ["+TB_RapidFire"] = true,
    ["+TB_Speed"] = true,
    ["Spam_Props-V2"] = true,
    ["Spam_Chat-v2"] = true,
    ["+bc_aimbot"] = true,
    ["-bc_aimbot"] = true,
    ["+bc_spamprops"] = true,
    ["bc_ips"] = true,
    ["+bc_speedshoot"] = true,
    ["bc_reload"] = true,
    ["wots_attack"] = true,
    ["_fap_reload"] = true,
    ["SE_AddFile"] = true,
    ["SE_RemoveFile"] = true,
    ["SE_LoadScripts"] = true,
    ["+pb_aim"] = true,
    ["pb_menu"] = true,
    ["Spam_Props"] = true,
    ["Spam_Chat"] = true,
    ["+li_aim"] = true,
    ["+li_menu"] = true,
    ["li_menu"] = true,
    ["+sh_menu"] = true,
    ["+Mawpos"] = true,
    ["gzfaimbot_reload"] = true,
    ["gzfaimbot_toggle"] = true,
    ["gzfaimbot_enabled"] = true,
    ["asb_base_reload"] = true,
    ["asb_base_unload"] = true,
    ["+shenbot_aimbot"] = true,
    ["shenbot_menu"] = true,
    ["shenbot_bunnyhoptoggle"] = true,
    ["-shenbot_aimbot"] = true,
    ["SpinBot_on"] = true,
    ["aimbot_off"] = true,
    ["_aimbot"] = true,
    ["lua_dofile_cl"] = true,
    ["lua_dostring_cl"] = true,
    ["ph0ne_aim"] = true,
    ["ph0ne_aimcancel"] = true,
    ["ph0ne_autoshoot"] = true,
    ["+trooper_menu"] = true,
    ["BMpublicaimbot_reload"] = true,
    ["BMpublicaimbot_toggle"] = true,
    ["+BMaimbot"] = true,
    ["BMpublicaimbot_menu"] = true,
    ["spamchat"] = true,
    ["_fap_menu_reload"] = true,
    ["rs"] = true,
    ["sh_triggerbot"] = true,
    ["sh_showips"] = true,
    ["+sh_speed"] = true,
    ["+sh_aim"] = true,
    ["sh_toggleaim"] = true,
    ["helix_chatspammer"] = true,
    ["helix_undo"] = true,
    ["helix_propspam"] = true,
    ["helix_admins"] = true,
    ["helix_rpnamespammer"] = true,
    ["+helix_speed"] = true,
    ["helix_crypto_binary"] = true,
    ["helix_forcerandomname_on"] = true,
    ["helix_forcerandomname_off"] = true,
    ["helix_troll"] = true,
    ["+helix_aim"] = true,
    ["helix_cvarmenu"] = true,
    ["formatlaser"] = true,
    ["+Helix_Menu"] = true,
    ["helix_reload"] = true,
    ["helix_propspammer2"] = true,
    ["helix_barrelbomb"] = true,
    ["helix_unload"] = true,
    ["helix_speed"] = true,
    ["helix_blocklua"] = true,
    ["helix_propspam_mdl"] = true,
    ["helix_aim_bone"] = true,
    ["helix_aim_crosshair"] = true,
    ["helix_aim_fov"] = true,
    ["helix_aim_los"] = true,
    ["helix_aim_norecoil"] = true,
    ["helix_aim_players"] = true,
    ["helix_aim_shoot"] = true,
    ["helix_aim_team"] = true,
    ["helix_aim_trigger"] = true,
    ["h_name"] = true,
    ["+bb_menu"] = true,
    ["bb"] = true,
    ["ForceLaunch_BB"] = true,
    ["jonsuite_unblockx"] = true,
    ["bacon_lua_openscript"] = true,
    ["discord1"] = true,
    ["discord2"] = true,
    ["aa_toggle"] = true,
    ["Bacon_TriggerBotDelay"] = true,
    ["Bacon_load"] = true,
    ["bacon_chatspam"] = true,
    ["bacon_namechange"] = true,
    ["bacon_chatspam_interval"] = true,
    ["bacon_norecoil"] = true,
    ["Bacon_AntiSnap"] = true,
    ["bacon_autoreload"] = true,
    ["+hermes_menu"] = true,
    ["+sykranos_is_luaviewerier_then_hex"] = true,
    ["sykranos_is_luaviewery_menu"] = true,
    ["+hermes_speed"] = true,
    ["AGT_AutoshootToggle"] = true,
    ["AGT_AimBotToggle"] = true,
    ["AGT_RandomName"] = true,
    ["nbot_aimfixer"] = true,
    ["nbot_speedoffset"] = true,
    ["nbot_UseSelectedPerson"] = true,
    ["nbot_autoshoot"] = true,
    ["fap_enablekeybinding"] = true,
    ["fap_bind"] = true,
    ["fap_unbind"] = true,
    ["lua_se2_load"] = true,
    ["ah_cheats"] = true,
    ["ah_changer"] = true,
    ["ah_speed"] = true,
    ["ah_aimbot_friends"] = true,
    ["ah_aimbot"] = true,
    ["ah_hooks"] = true,
    ["ah_hookhide"] = true,
    ["ah_name"] = true,
    ["ah_antihook"] = true,
    ["ah_reload"] = true,
    ["ah_timestop"] = true,
    ["setconvar"] = true,
    ["fap_menu"] = true,
    ["fap_checkforupdates"] = true,
    ["fap_aim"] = true,
    ["+fap_aim"] = true,
    ["fap_aim_toggle"] = true,
    ["lua_openscript_cl2"] = true,
    ["raidbot_predictcheck"] = true,
    ["aa_enabled"] = true,
    ["BMaimbot"] = true,
    ["aimbot_headshots_on"] = true,
    ["CBon_Reload_Script"] = true,
    ["+CBon_menu"] = true,
    ["ah_chatspammer"] = true,
    ["ah_spammer"] = true,
    ["+ah_menu"] = true,
    ["+nbot_options"] = true,
    ["sm_fexec"] = true,
    ["GAT_RandomName"] = true,
    ["name_menu"] = true,
    ["namechanger_on"] = true,
    ["cl_name"] = true,
    ["+wots_toggleimmunity"] = true,
    ["send_file"] = true,
    ["Bacon_Reload_Script"] = true,
    ["fap_reload"] = true,
    ["download_file"] = true,
    ["upload_file"] = true,
    ["plugin_load"] = true,
    ["sethhack_load"] = true,
    ["st_jumpspam"] = true,
    ["force_cvar"] = true,
    ["cl_docrash"] = true,
    ["_fap_initshit"] = true,
    ["+namechanger"] = true,
    ["RandomNCOn"] = true,
    ["BlankNCON"] = true,
    ["PsaySpamOn"] = true,
    ["GayOn"] = true,
    ["RatingSpammerOn"] = true,
    ["+jbf_scan"] = true,
    ["kennykill"] = true,
    ["kenny_team"] = true,
    ["kenny_bodyshots"] = true,
    ["+kenny"] = true,
    ["kenny_tagasshole"] = true,
    ["kenny_addhit"] = true,
    ["Kenny_noclip"] = true,
    ["bacon_toggle"] = true,
    ["Bacon_EntTriggerBot"] = true,
    ["+wots_spinhack"] = true,
    ["wots_spinhack"] = true,
    ["wire_button_model"] = true,
    ["lol_togglestick"] = true,
    ["lol_name"] = true,
    ["lol_copy"] = true,
    ["lol_fuckthis"] = true,
    ["lol_barrel"] = true,
    ["lol_setchat"] = true,
    ["lol_chat"] = true,
    ["lol_help"] = true,
    ["lol_admins"] = true,
    ["lol_adminalert"] = true,
    ["lol_cancel"] = true,
    ["lol_aim"] = true,
    ["lol_headshot"] = true,
    ["lol_teamshot"] = true,
    ["wots_namecracker_menu"] = true,
    ["wots_namecracker_on"] = true,
    ["wots_namecracker_off"] = true,
    ["wots_crash"] = true,
    ["wots_lag_on"] = true,
    ["wots_lag_off"] = true,
    ["speedhack_speed"] = true,
    ["SetCV"] = true,
    ["+wowspeed"] = true,
    ["+gofast"] = true,
    ["+goslow"] = true,
    ["JBF_off"] = true,
    ["JBF_on"] = true,
    ["JBF_headshots_off"] = true,
    ["skid"] = true,
    ["JBF_headshots_on"] = true,
    ["JBF_enemysonly_on"] = true,
    ["JBF_enemysonly_off"] = true,
    ["JBF_playersonly_on"] = true,
    ["JBF_playersonly_off"] = true,
    ["_JBF_lagcompensation"] = true,
    ["JBF_lagcompensation"] = true,
    ["JBF_suicidehealth"] = true,
    ["JBF_offset"] = true,
    ["+BUTTFUCK"] = true,
    ["entx_spazon"] = true,
    ["entx_spazoff"] = true,
    ["entx_setvalue"] = true,
    ["+buttfuck"] = true,
    ["fap_aim_enabled"] = true,
    ["fap_aim_friendlyfire"] = true,
    ["fap_aim_targetnpcs"] = true,
    ["fap_aim_autofire"] = true,
    ["fap_aim_autoreload"] = true,
    ["fap_aim_bonemode"] = true,
    ["fap_aim_targetfriends"] = true,
    ["fap_aim_targetsteamfriends"] = true,
    ["fap_aim_targetmode"] = true,
    ["fap_aim_nospread"] = true,
    ["fap_aim_maxdistance"] = true,
    ["fap_aim_targetadmins"] = true,
    ["fap_aim_antisnap"] = true,
    ["fap_aim_norecoil"] = true,
    ["fap_aim_antisnapspeed"] = true,
    ["niggeron"] = true,
    ["niggerff"] = true,
    ["niggerfl"] = true,
    ["niggersz"] = true,
    ["niggernpc"] = true,
    ["niggerw"] = true,
    ["niggeri"] = true,
    ["niggershd"] = true,
    ["niggermxsh"] = true,
    ["niggershit"] = true,
    ["niggersd"] = true,
    ["NameGenDerma"] = true,
    ["+elebot"] = true,
    ["+leetbot"] = true,
    ["elebot_offset"] = true,
    ["leetbot_offset"] = true,
    ["elebot_minview"] = true,
    ["leetbot_minview"] = true,
    ["elebot_maxview"] = true,
    ["leetbot_maxview"] = true,
    ["elebot_boxsize"] = true,
    ["leetbot_boxsize"] = true,
    ["elebot_simplecolors"] = true,
    ["leetbot_simplecolors"] = true,
    ["elebot_targetteam"] = true,
    ["leetbot_targetteam"] = true,
    ["elebot_showadmin"] = true,
    ["leetbot_showadmin"] = true,
    ["elebot_filledbox"] = true,
    ["leetbot_filledbox"] = true,
    ["+wots_menu"] = true,
    ["wots_menu"] = true,
    ["wots_megaspam"] = true,
    ["wots_namegen_on"] = true,
    ["wots_namegen_off"] = true,
    ["name_change"] = true,
    ["change_name"] = true,
    ["name_changer"] = true,
    ["+name_changer"] = true,
    ["+Bacon_Menu"] = true,
    ["+BaconToggle"] = true,
    ["BaconToggle"] = true,
    ["Bacon_triggerbot_toggle"] = true,
    ["+Bacon_triggerbot_toggle"] = true,
    ["Bacon_FF_Toggle"] = true,
    ["aimbot_scan"] = true,
    ["+aimbot_scan"] = true,
    ["aimbot"] = true,
    ["_aimbot_headshots"] = true,
    ["aimbot_offset"] = true,
    ["entx_run1"] = true,
    ["entx_run2"] = true,
    ["entx_run3"] = true,
    ["entx_run4"] = true,
    ["entx_traceget"] = true,
    ["entx_camenable"] = true,
    ["+slobpos"] = true,
    ["Bacon_Trigger_Bot"] = true,
    ["+Bacon_Trigger_Bot"] = true,
    ["Bacon_Ignore_SteamFriends"] = true,
    ["Bacon_Mode"] = true,
    ["+gzfaimbot"] = true,
    ["gzfaimbot"] = true,
    ["gzfaimbot_menu"] = true,
    ["at_changer_on"] = true,
    ["at_changer_off"] = true,
    ["at_norecoil_on"] = true,
    ["at_norecoil_off"] = true,
    ["at_menu"] = true,
    ["_GBot_Off"] = true,
    ["_GBot_Menu"] = true,
    ["at_autoshoot_on"] = true,
    ["at_autoshoot_off"] = true,
    ["aa_reload"] = true,
    ["+aa"] = true,
    ["aa_menu"] = true,
    ["+nBot"] = true,
    ["+nbot_Options"] = true,
    ["nbot_Options"] = true,
    ["aimbot_on"] = true,
    ["aimbot_hitbox"] = true,
    ["aimbot_target_teamates"] = true,
    ["aimbot_target_closest"] = true,
    ["aimbot_target_clear"] = true,
    ["+asb_bot"] = true,
    ["asb_bot"] = true,
    ["asb_options"] = true,
    ["+asb"] = true,
    ["asb"] = true,
    ["asb_unload"] = true,
    ["asb_reload"] = true,
    ["asb_shoot"] = true,
    ["+entinfo"] = true,
    ["entinfo_target"] = true,
    ["asb_nospread"] = true,
    ["asb_players"] = true,
    ["entinfo_targetplayer"] = true,
    ["AHack_Menu"] = true,
    ["bs_namechange"] = true,
    ["bs_file"] = true,
    ["bs_spoofcvar"] = true,
    ["AnXition_Menu"] = true,
    ["AnXition_Boost1"] = true,
    ["book"] = true,
    ["AnXition_Boost2"] = true,
    ["AnXition_Boost3"] = true,
    ["AnXition_Derp"] = true,
    ["AnXition_Follow"] = true,
    ["AnXition_GetDClasses"] = true,
    ["AnXition_GetClass"] = true,
    ["AHack_"] = true,
    ["mapex"] = true,
    ["+sykranos_is_luaviewery"] = true,
    ["+sykranos_is_really_luaviewery"] = true,
    ["lol_****this"] = true,
    ["+*********"] = true,
    ["******on"] = true,
    ["******ff"] = true,
    ["******fl"] = true,
    ["******sz"] = true,
    ["******npc"] = true,
    ["******w"] = true,
    ["******i"] = true,
    ["******shd"] = true,
    ["******mxsh"] = true,
    ["***********"] = true,
    ["******sd"] = true,
    ["lenny_menu"] = true,
    ["+Sethhacks_Aim"] = true,
    ["+Sethhacks_Menu"] = true,
    ["+Sethhacks_Speed"] = true,
    ["+save_replay"] = true,
    ["+sykranos_is_really_sexy"] = true,
    ["+sykranos_is_sexier_then_hex"] = true,
    ["+sykranos_is_sexy"] = true,
    ["+ubot_viser"] = true,
    ["-ubot_viser"] = true,
    ["ahack_menu"] = true,
    ["sykranos_is_sexy_menu"] = true,
    ["loki_menu"] = true,
    ["cheadle_api"] = true,
    ["gear_printents"] = true,
    ["gw_toggle"] = true,
    ["gw_pos"] = true,
    ["gearmenu"] = true,
    ["gb_reload"] = true,
    ["gb_toggle"] = true,
    ["+gb"] = true,
    ["-gb"] = true,
    ["gb_menu"] = true,
    ["gear2_menu"] = true,
    ["sasha_menu"] = true,
    ["showents"] = true,
    ["showhxmenu"] = true,
    ["SmegHack_Menu"] = true,
    ["sCheat_menu"] = true,
    ["lowkey_menu"] = true,
}

local HackGlobals = {
    ["netCodes"] = true,
    ["hack"] = true,
    ["cheat"] = true,
    ["aimbot"] = true,
    ["wallhack"] = true,
    ["mapex"] = true,
    ["bunnyhop"] = true,
    ["xray"] = true,
    ["norecoil"] = true,
    ["nospread"] = true,
    ["drawesp"] = true,
    ["doesp"] = true,
    ["manipulate_spread"] = true,
    ["hl2_shotmanip"] = true,
    ["hl2_ucmd_getprediciton"] = true,
    ["cf_manipulateShot"] = true,
    ["zedhack"] = true,
    ["triggerbot"] = true,
    ["getpred"] = true,
    ["cheadle_api"] = true,
    ["bSendPacket"] = true,
    ["ValidNetString"] = true,
    ["totalExploits"] = true,
    ["addExploit"] = true,
    ["AutoReload"] = true,
    ["CircleStrafe"] = true,
    ["toomanysploits"] = true,
    ["Sploit"] = true,
    ["R8"] = true,
    ["ValidateESP"] = true,
    ["ValidateAimbot"] = true,
}

local BadCVars = {
    ["snixzz"] = true,
    ["razor_aim"] = true,
    ["bonus_sv_cheats"] = true,
    ["bonus_sv_allowcslua"] = true,
    ["sp00f_sv_cheats"] = true,
    ["bs_sv_cheats"] = true,
    ["sp00f_sv_allowcslua"] = true,
    ["ah_sv_cheats"] = true,
    ["ah_sv_allowcslua"] = true,
    ["ah_cheats"] = true,
    ["ah_timescale"] = true,
    ["dead_chams"] = true,
    ["dead_xray"] = true,
    ["mh_rearview"] = true,
    ["zedhack"] = true,
    ["boxbot"] = true,
    ["damnbot_"] = true,
    ["ahack_active"] = true,
    ["ahack_aimbot_active"] = true,
    ["mapex_showadmins"] = true,
    ["mapex_speedhack_speed"] = true,
    ["mapex_dancin"] = true,
    ["mapex_xray"] = true,
    ["damnbot_esp_info"] = true,
    ["damnbot_esp_box"] = true,
    ["damnbot_misc_bunnyhop"] = true,
    ["damnbot_aim_aimspot"] = true,
    ["fap_esp_radar"] = true,
    ["fap_bunnyhopspeed"] = true,
    ["fap_checkforupdates"] = true,
    ["fap_aim_autoreload"] = true,
    ["fap_aim_enabled"] = true,
    ["fap_aim_bonemode"] = true,
    ["b-hacks_misc_bhop"] = true,
    ["hera_esp_chams"] = true,
    ["traffichack_aimbot_active"] = true,
    ["traffichack_aimbot_randombones"] = true,
    ["lenny_triggerbot"] = true,
    ["lenny_aimsnap"] = true,
    ["lenny_wh"] = true,
    ["dead_esp"] = true,
    ["niggermenu_Active"] = true,
    ["executer"] = true,
    ["neko_list"] = true,
    ["htx_silent"] = true,
    ["htx_mode"] = true,
    ["lix_lesp_sayprefix"] = true,
    ["lix_lesp_on"] = true,
    ["lix_lesp_health"] = true,
    ["lix_lesp_weapon"] = true,
    ["lix_lesp_money"] = true,
    ["lix_lesp_distance"] = true,
    ["lix_lesp_speed"] = true,
    ["lix_lesp_mirror"] = true,
    ["lix_lesp_mirrorx"] = true,
    ["lix_lesp_mirrory"] = true,
    ["lix_lesp_mirrorw"] = true,
    ["lix_lesp_mirrorh"] = true,
    ["lix_lesp_mirrorpitch"] = true,
    ["lix_lesp_mirroryaw"] = true,
    ["lix_lesp_mirrorroll"] = true,
    ["lix_lesp_radar"] = true,
    ["lix_lesp_radary"] = true,
    ["lix_lesp_radarx"] = true,
    ["lix_lesp_radarw"] = true,
    ["lix_lesp_radarh"] = true,
    ["lix_lesp_radarfov"] = true,
    ["lix_lesp_radarauto"] = true,
    ["lix_lesp_aimdot"] = true,
    ["lix_lesp_aimdotfilter"] = true,
    ["lix_lesp_votetime"] = true,
    ["lix_lesp_detectshow"] = true,
    ["lix_lesp_detectshowrad"] = true,
    ["lix_lesp_detectthresh"] = true,
    ["lix_lesp_detecttrace"] = true,
    ["lix_lesp_xraymat"] = true,
    ["lix_lesp_chatreverse"] = true,
    ["lix_lesp_chatcambridge"] = true,
    ["lix_lesp_chatbyte"] = true,
    ["lix_lesp_objects"] = true,
    ["falco_xraymaterial"] = true,
    ["falco_xrayPROPColor"] = true,
    ["falco_xrayPROPBGColor"] = true,
    ["falco_xrayMINEColor"] = true,
    ["falco_xrayHOLDINGColor"] = true,
    ["falco_xrayPROPMINEBGColor"] = true,
    ["falco_xrayPLAYERcolor"] = true,
    ["gravko_esp"] = true,
    ["gmhax_ShowUnknownEntity"] = true,
    ["gmhax_showdarkrploot2"] = true,
    ["silent"] = true,
    ["aim"] = true,
    ["esp"] = true,
    ["esp_printer"] = true,
    ["esp_dis"] = true,
    ["esp_transparancy"] = true,
    ["esp_info"] = true,
    ["aim_dis"] = true,
    ["bhop"] = true,
    ["AHack_Active"] = true,
    ["mapex_rpgod"] = true,
    ["mapex_showspecs"] = true,
    ["mapex_sniper"] = true,
    ["mapex_weed"] = true,
    ["mapex_coke"] = true,
    ["mapex_printer"] = true,
    ["mapex_gmodz"] = true,
    ["mapex_norecoil"] = true,
    ["mapex_lazer"] = true,
    ["mapex_dd"] = true,
    ["mapex_box"] = true,
    ["mapex_ulxgag"] = true,
    ["B-Hacks_Lasers_HeadLasers"] = true,
    ["B-Hacks_Misc_BlackSkyBox"] = true,
    ["B-Hacks_Misc_FlashLightSpam"] = true,
    ["B-Hacks_Misc_Bhop"] = true,
    ["fap_aim_friendlyfire"] = true,
    ["fap_aim_targetnpcs"] = true,
    ["fap_aim_onlyenemynpcs"] = true,
    ["lenny_advcrosshair"] = true,
    ["lenny_advcrosshair_money"] = true,
    ["lenny_hud"] = true,
    ["triggerbot"] = true,
    ["aimbot"] = true,
    ["aimx"] = true,
    ["aimbot_enabled"] = true,
    ["fap_speedhack_speed"] = true,
    ["vh_speedhack_speed"] = true,
    ["vh_silentaim"] = true,
    ["vh_trigger"] = true,
    ["vh_nospread"] = true,
    ["vh_steamfriends"] = true,
    ["vh_friendly"] = true,
    ["vh_ignoreadmins"] = true,
    ["vh_antisnap"] = true,
    ["vh_antisnap_speed"] = true,
    ["vh_aim_offset"] = true,
    ["CV_CHEATS"] = true,
    ["____sv_cheats"] = true,
    ["____host_timescale"] = true,
    ["____sv_consistency"] = true,
    ["____mat_fullbright"] = true,
    ["bktb_friendly_fire"] = true,
    ["bktb_max_distance"] = true,
    ["bktb"] = true,
    ["speedhack_multiplier"] = true,
    ["bk_aimbot_autoshoot"] = true,
    ["bk_aimbot_ignore_steam_friends"] = true,
    ["bk_aimbot_ignore_teammates"] = true,
    ["bk_aimbot_use_friend_and_enemy_list"] = true,
    ["bk_aimbot_silent"] = true,
    ["bk_aimbot_silent_smooth"] = true,
    ["bk_crosshair_actual_aim"] = true,
    ["bk_norecoil"] = true,
    ["bk_nospread"] = true,
    ["bk_smoothlook"] = true,
    ["bk_spinbot"] = true,
    ["bk_spinbot_random"] = true,
    ["mechgear_aimbot"] = true,
    ["mechgear_aimbot_onattack"] = true,
    ["mechgear_aimbot_useminimumoncommand"] = true,
    ["mechgear_aimbot_minimum"] = true,
    ["_ihack_esp"] = true,
    ["_ihack_esp_npcs"] = true,
    ["_ihack_esp_players"] = true,
    ["_ihack_esp_weapons"] = true,
    ["_ihack_esp_charms"] = true,
    ["_ihack_esp_laser"] = true,
    ["_ihack_aimbot_ignoreplayers"] = true,
    ["_ihack_aimbot_ignorenpcs"] = true,
    ["_ihack_aimbot_ignorefriends"] = true,
    ["_ihack_aimbot_ignoreadmins"] = true,
    ["_ihack_aimbot_friendlyfire"] = true,
    ["_ihack_aimbot_auto"] = true,
    ["_ihack_aimbot_fakeview"] = true,
    ["_ihack_aimbot_nospread"] = true,
    ["_ihack_misc_alwaysnospread"] = true,
    ["_ihack_misc_fov"] = true,
    ["_ihack_misc_disconnectmsg"] = true,
    ["_ihack_ttt_showbodys"] = true,
    ["_ihack_ttt_ignorefellowdetectives"] = true,
    ["_ihack_ttt_ignorefellowtraitors"] = true,
    ["Aim_Enabled"] = true,
    ["Aim_NoRecoil"] = true,
    ["Misc_Spam"] = true,
    ["AC_Misc_Bhop"] = true,
    ["Coma_Misc_LogIPs"] = true,
    ["Coma_Misc_ULXAntiGag"] = true,
    ["Coma_Misc_Date"] = true,
    ["Coma_Misc_Spammer"] = true,
    ["Coma_SlowSpeedHack"] = true,
    ["Coma_SH_CheatsOff"] = true,
    ["Coma_SHSpeed"] = true,
    ["Coma_HostFrameRate"] = true,
    ["Coma_HostTimeScale"] = true,
    ["Coma_AimBot_SmoothAim"] = true,
    ["Coma_AimBot_SmoothAimSpeed"] = true,
    ["Coma_AimBot_Autoshoot"] = true,
    ["Coma_AimBot_NoRecoil"] = true,
    ["Coma_AimBot_NoSpread"] = true,
    ["Coma_AimBot_IgnoreSteamFriends"] = true,
    ["Coma_AimBot_IgnoreAdmins"] = true,
    ["Coma_AimBot_FriendlyFire"] = true,
    ["Coma_AimBot_IgnoreTraitorFriends"] = true,
    ["SB_Aim_Enabled"] = true,
    ["hake_shouldrun"] = true,
    ["SB_Aim_FF"] = true,
    ["SB_Aim_Offset"] = true,
    ["SB_Aim_Steam"] = true,
    ["SB_Aim_NoRecoil"] = true,
    ["SB_Misc_Spam"] = true,
    ["fhack"] = true,
    ["fhackmodel"] = true,
    ["fhackrage"] = true,
    ["anthrax_killonsight"] = true,
    ["anthrax_velocitypredict"] = true,
    ["Smelly_Misc_LogIPs"] = true,
    ["metalslave_aimbot_enabled"] = true,
    ["mh_ab_enabled"] = true,
    ["mh_ab_ffa"] = true,
    ["mh_ab_nospread"] = true,
    ["mh_ab_priority"] = true,
    ["mh_ab_fov"] = true,
    ["mh_ab_offset"] = true,
    ["mh_ab_auto"] = true,
    ["mh_esp_enabled"] = true,
    ["mh_esp_mode"] = true,
    ["mh_esp_names"] = true,
    ["mh_esp_health"] = true,
    ["mh_esp_reveal"] = true,
    ["mh_esp_revent"] = true,
    ["mh_esp_fov"] = true,
    ["mh_ungag"] = true,
    ["cf_host_timescale"] = true,
    ["cf_aim_enabled"] = true,
    ["cf_bunnyhop_minspeed"] = true,
    ["cf_lockdownlua"] = true,
    ["cf_checkdormantplayers"] = true,
    ["cf_bunnyhopspace"] = true,
    ["cf_bunnyhop"] = true,
    ["cf_collectgarbage"] = true,
    ["cf_pingpredict"] = true,
    ["cf_updatemenucomponents"] = true,
    ["cf_logs_level"] = true,
    ["cf_logs_enabled"] = true,
    ["cf_traitormode"] = true,
    ["cf_spinbot"] = true,
    ["cf_esp_drawcrosshair"] = true,
    ["cf_esp_usesmallerfont"] = true,
    ["cf_esp_drawtextinfo"] = true,
    ["cf_esp_drawweapons"] = true,
    ["cf_esp_drawmodels"] = true,
    ["cf_esp_outlinemodels"] = true,
    ["cf_esp_draweyeangles"] = true,
    ["cf_esp_minespdistance"] = true,
    ["cf_esp_maxespdistance"] = true,
    ["cf_esp_entitytransparencydiameter"] = true,
    ["cf_esp_entitytranspare"] = true,
    ["cf_esp_enabled"] = true,
    ["cf_esp_onlydrawtraitors"] = true,
    ["cf_aim_nospreadonfire"] = true,
    ["cf_aim_ucmdfire"] = true,
    ["cf_aim_snaponfiretime"] = true,
    ["cf_aim_snaponfire"] = true,
    ["cf_aim_offsetz"] = true,
    ["cf_aim_predictionseed"] = true,
    ["cf_aim_nospread"] = true,
    ["cf_aim_enemymode"] = true,
    ["cf_aim_autoreload"] = true,
    ["cf_aim_autofire"] = true,
    ["cf_aim_checkpartialhits"] = true,
    ["cf_aim_fakeview"] = true,
    ["cf_aim_antisnapspeed"] = true,
    ["cf_aim_antisnap"] = true,
    ["cf_aim_velocityprediction"] = true,
    ["cf_aim_ignorelos"] = true,
    ["cf_aim_maxangledifference"] = true,
    ["cf_aim_bonemode"] = true,
    ["cf_aim_targetmode"] = true,
    ["cf_aim_onlytargettraitors"] = true,
    ["cf_aim_targetsteamfriends"] = true,
    ["cf_aim_targetadmins"] = true,
    ["cf_aim_targetfriends"] = true,
    ["cf_aim_friendlyfire"] = true,
    ["cf_aim_targetnpcs"] = true,
    ["cf_aim_maxdistance"] = true,
    ["Isis_Esp"] = true,
    ["Isis_Esp_Health"] = true,
    ["Isis_Esp_Box"] = true,
    ["Isis_Esp_Warnings"] = true,
    ["Isis_Esp_Traitor"] = true,
    ["Isis_Esp_Admins"] = true,
    ["Isis_Esp_ShowC4"] = true,
    ["Isis_Esp_Chams"] = true,
    ["Isis_Misc_AntiGag"] = true,
    ["Isis_Misc_ShowStatus"] = true,
    ["Isis_Misc_Bunnyhop"] = true,
    ["Isis_Misc_RemoveSky"] = true,
    ["Isis_Misc_Crosshair"] = true,
    ["Isis_Aimbot_NoRecoil"] = true,
    ["Isis_Aimbot_IgnoreSteam"] = true,
    ["Isis_Aimbot_Friendlyfire"] = true,
    ["Isis_Aimbot_FixView"] = true,
    ["Isis_Aimbot_AutoShoot"] = true,
    ["Isis_Aimbot_NoSpread"] = true,
    ["Isis_Aimbot_Offset"] = true,
    ["Isis_Aimbot_AimSpot"] = true,
    ["Isis_Speedhack_Speed"] = true,
    ["Isis_Other_AutoReminder"] = true,
    ["qq_ttt_predict_nade"] = true,
    ["qq_antiaim_mode"] = true,
    ["qq_fakeview_enabled"] = true,
    ["qq_debug"] = true,
    ["aah_log"] = true,
    ["aah_logpath"] = true,
    ["aah_blockac"] = true,
    ["aah_bypassse"] = true,
    ["aah_hash"] = true,
    ["DragonBot_Esp"] = true,
    ["DragonBot_Esp_Health"] = true,
    ["DragonBot_Esp_Distance"] = true,
    ["DragonBot_Esp_Admin"] = true,
    ["DragonBot_Bhop"] = true,
    ["DragonBot_Rp_Esp"] = true,
    ["DragonBot_Chams"] = true,
    ["DragonBot_Line"] = true,
    ["DragonBot_Light"] = true,
    ["DragonBot_Trigger"] = true,
    ["DragonBot_TTT"] = true,
    ["DragonBot_Aimbot_IgnoreSteam"] = true,
    ["DragonBot_Aimbot_Friendlyfire"] = true,
    ["DragonBot_Aimbot_IgnoreAdmins"] = true,
    ["DragonBot_SmoothAim_Enabled"] = true,
    ["DragonBot_Smooth_Speed"] = true,
    ["DragonBot_Aimbot_Norecoil"] = true,
    ["DragonBot_AimKeySave"] = true,
    ["DragonBot_MenuKeySave"] = true,
    ["DragonBot_PropKeySave"] = true,
    ["triggerbot_enabled"] = true,
    ["asb_bone"] = true,
    ["asb_fov"] = true,
    ["asb_los"] = true,
    ["asb_players"] = true,
    ["asb_shoot"] = true,
    ["asb_trigger"] = true,
    ["sw_aim"] = true,
    ["sw_norecoil"] = true,
    ["sw_aimonfire"] = true,
    ["sh_aim"] = true,
    ["sh_aimonfire"] = true,
    ["sh_norecoil"] = true,
    ["anacletobot"] = true,
    ["anacletobot_target"] = true,
    ["anacletobot_maxdist"] = true,
    ["+ares_aim"] = true,
    ["ink_propkill"] = true,
    ["sh_print_traitors"] = true,
    ["Ares_Misc_Bhop"] = true,
    ["Ares_Misc_Keypad"] = true,
    ["Ares_Misc_LogIPs"] = true,
    ["Ares_Misc_ULXAntiGag"] = true,
    ["Ares_Traitor"] = true,
    ["Ares_ESP_C4Detection"] = true,
    ["Ares_SlowSpeedHack"] = true,
    ["Ares_SH_CheatsOff"] = true,
    ["Ares_SHSpeed"] = true,
    ["Ares_HostFrameRate"] = true,
    ["Ares_HostTimeScale"] = true,
    ["Ares_AimBot_SmoothAim"] = true,
    ["Ares_AimBot_SmoothAimSpeed"] = true,
    ["Ares_AimBot_Autoshoot"] = true,
    ["Ares_AimBot_NoRecoil"] = true,
    ["Ares_AimBot_NoSpread"] = true,
    ["Ares_AimBot_IgnoreSteamFriends"] = true,
    ["Ares_AimBot_IgnoreAdmins"] = true,
    ["Ares_AimBot_FriendlyFire"] = true,
    ["Ares_AimBot_IgnoreTraitorFriends"] = true,
    ["ms_host_timescale"] = true,
    ["ms_sv_cheats"] = true,
    ["MAim_Targetmode"] = true,
    ["MAim_MaxDistance"] = true,
    ["MAim_MaxAngle"] = true,
    ["MAim_FF"] = true,
    ["MAim_Autoshoot"] = true,
    ["MAim_MissShots"] = true,
    ["MAim_Antisnap"] = true,
    ["MAim_AntisnapSpeed"] = true,
    ["M_Norecoil"] = true,
    ["M_NoSpread"] = true,
    ["speedhack_speed"] = true,
    ["x_enabled"] = true,
    ["Hax_NameTags"] = true,
    ["Hax_SaveView"] = true,
    ["Hax_ShowCrosshair"] = true,
    ["Hax_ShowCrosshair2"] = true,
    ["Hax_WallHackStyle"] = true,
    ["Hax_SmoothAim"] = true,
    ["Hax_SmoothAimSpeed"] = true,
    ["Hax_DrawParticles"] = true,
    ["Hax_TriggerBot"] = true,
    ["Hax_TriggerBot2"] = true,
    ["Hax_IgnoreSteamFriends"] = true,
    ["Hax_MaxWallHackDist"] = true,
    ["Hax_IgnoreTeam"] = true,
    ["Hax_AimFov"] = true,
    ["TB_AimFov"] = true,
    ["TB_AimTeam"] = true,
    ["TB_NameTags"] = true,
    ["TB_NTAdmin"] = true,
    ["TB_NTHealth"] = true,
    ["TB_NTAlpha"] = true,
    ["TB_FakeView"] = true,
    ["TB_TargetPlayers"] = true,
    ["TB_TargetNPCs"] = true,
    ["TB_AntiSnap"] = true,
    ["TB_AntiSnapSpeed"] = true,
    ["AimAssistSA"] = true,
    ["AimAssistFV"] = true,
    ["ATTargetPlayers"] = true,
    ["ATTargetNPCs"] = true,
    ["ATIgnoreSteam"] = true,
    ["ATIgnoreDistance"] = true,
    ["ATAimDistance"] = true,
    ["ATWallHack"] = true,
    ["ATAimRadius"] = true,
    ["ATNPCNames"] = true,
    ["h_sv_cheats"] = true,
    ["h_host_timescale"] = true,
    ["h_host_framerate"] = true,
    ["lymes_enable_hack_killhead_shotter"] = true,
    ["lymes_enable_seethrough_esphack"] = true,
    ["lymes_remotelua_hake"] = true,
    ["lymes_remotelua_hack"] = true,
    ["lymes_enable_autoheadshoot"] = true,
    ["Neon_AimBot_ShowAimStatus"] = true,
    ["Neon_AimBot_SmoothAimEnabled"] = true,
    ["Neon_AimBot_SmoothAimSpeed"] = true,
    ["Neon_AimBot_IgnoreFriends"] = true,
    ["Neon_AimBot_IgnoreAdmins"] = true,
    ["Neon_AimBot_Friendlyfire"] = true,
    ["Neon_AimBot_NoRecoil"] = true,
    ["Neon_AimBot_AimOffset"] = true,
    ["Neon_AimBot_AimBone"] = true,
    ["Neon_AimBot_AimMode"] = true,
    ["Neon_AimBot_IgnoreSteamFriends"] = true,
    ["Neon_PlayerESP"] = true,
    ["Neon_PlayerESP_Health"] = true,
    ["Neon_PlayerESP_ShowAll"] = true,
    ["Neon_NPCESP"] = true,
    ["Neon_PlayerFullBright"] = true,
    ["Neon_PlayerWireFrame"] = true,
    ["Neon_MoneyPrinterESP"] = true,
    ["Neon_MoneyESP"] = true,
    ["Neon_ShipmentESP"] = true,
    ["Neon_FullBright"] = true,
    ["Neon_Gray"] = true,
    ["Neon_WorldWireFrame"] = true,
    ["Neon_PlayerBox"] = true,
    ["Neon_Bhop"] = true,
    ["Neon_ULXAntiGag"] = true,
    ["Neon_NikeSpeed"] = true,
    ["Neon_HostTimeScale"] = true,
    ["Neon_SpeedHack_CheatsOff"] = true,
    ["Neon_Traitor"] = true,
    ["Neon_KeypadHack"] = true,
    ["Neon_WeaponsESP"] = true,
    ["Neon_AimBot_TriggerBot"] = true,
    ["Neon_PlayerWallHackFull"] = true,
    ["Neon_DynamicLight"] = true,
    ["Neon_DynamicLightSize"] = true,
    ["Neon_LogPlayerIPs"] = true,
    ["Neon_CrossHair"] = true,
    ["Neon_CrossHair_Red"] = true,
    ["Neon_CrossHair_Green"] = true,
    ["Neon_CrossHair_Blue"] = true,
    ["Neon_C4Detection"] = true,
    ["hermes_misc_antiaimr_antiaim"] = true,
    ["hermes_misc_antiaimy_antiaim"] = true,
    ["hermes_misc_antiaimp_antiaim"] = true,
    ["hermes_misc_antiaimduck_antiaim"] = true,
    ["hermes_misc_antiaimrandom_antiaim"] = true,
    ["hermes_misc_antiaim_antiaim"] = true,
    ["hermes_misc_zoomamount_zoom"] = true,
    ["hermes_misc_zoomontrigger_zoom"] = true,
    ["hermes_misc_zoomonaim_zoom"] = true,
    ["hermes_misc_zoomalways_zoom"] = true,
    ["hermes_misc_zoom_zoom"] = true,
    ["hermes_misc_speedhackspeed_speedhack"] = true,
    ["hermes_misc_speedhack_speedhack"] = true,
    ["hermes_misc_particles_globals"] = true,
    ["hermes_misc_fullbrightg_globals"] = true,
    ["hermes_misc_radarradius_radar"] = true,
    ["hermes_misc_radarspin_radar"] = true,
    ["hermes_misc_radarname_radar"] = true,
    ["hermes_misc_radar_radar"] = true,
    ["hermes_misc_crosshairlength_crosshair"] = true,
    ["hermes_misc_crosshairgap_crosshair"] = true,
    ["hermes_misc_crosshair_crosshair"] = true,
    ["hermes_misc_crosshairtype_crosshair"] = true,
    ["hermes_misc_ulxantigag_misc"] = true,
    ["hermes_misc_autopistol_misc"] = true,
    ["hermes_misc_bunnyhop_misc"] = true,
    ["hermes_misc_namesteal_misc"] = true,
    ["hermes_esp_asusval_asus"] = true,
    ["hermes_esp_asusmdl_asus"] = true,
    ["hermes_esp_asus_asus"] = true,
    ["hermes_esp_visiblechams_chams"] = true,
    ["hermes_esp_fullbright_chams"] = true,
    ["hermes_esp_walltype_chams"] = true,
    ["hermes_esp_vehiclese_entities"] = true,
    ["hermes_esp_ragdollse_entities"] = true,
    ["hermes_esp_weaponse_entities"] = true,
    ["hermes_esp_entityliste_entities"] = true,
    ["hermes_esp_enablee_entities"] = true,
    ["hermes_esp_boxn_npcs"] = true,
    ["hermes_esp_enablen_npcs"] = true,
    ["hermes_esp_adminlist_players"] = true,
    ["hermes_esp_friendsmark_players"] = true,
    ["hermes_esp_barrel_players"] = true,
    ["hermes_esp_weapon_players"] = true,
    ["hermes_esp_health_players"] = true,
    ["hermes_esp_name_players"] = true,
    ["hermes_esp_enemyonly_players"] = true,
    ["hermes_esp_enable_players"] = true,
    ["hermes_esp_optical_players"] = true,
    ["hermes_esp_fadelength_general"] = true,
    ["hermes_esp_maxshow_general"] = true,
    ["hermes_esp_enablefade_general"] = true,
    ["hermes_esp_font_general"] = true,
    ["hermes_aim_novisspread_accuracy"] = true,
    ["hermes_aim_norecoil_accuracy"] = true,
    ["hermes_aim_nospread_accuracy"] = true,
    ["hermes_aim_togglename_hud"] = true,
    ["hermes_aim_toggle_hud"] = true,
    ["hermes_aim_triggerdistance_triggerbot"] = true,
    ["hermes_aim_triggernospread_triggerbot"] = true,
    ["hermes_aim_triggerkey_triggerbot"] = true,
    ["hermes_aim_triggerbot_triggerbot"] = true,
    ["hermes_aim_ignorevehicle_targeting"] = true,
    ["hermes_aim_ignoreghost_targeting"] = true,
    ["hermes_aim_ignoretraitor_targeting"] = true,
    ["hermes_aim_ignoreteam_targeting"] = true,
    ["hermes_aim_ignoresteam_targeting"] = true,
    ["hermes_aim_ignoreadmin_targeting"] = true,
    ["hermes_aim_targetnpc_targeting"] = true,
    ["hermes_aim_targetplayer_targeting"] = true,
    ["hermes_aim_friendslist_targeting"] = true,
    ["hermes_aim_predictply_aimbot"] = true,
    ["hermes_aim_predicttar_aimbot"] = true,
    ["hermes_aim_smoothaimspeed_aimbot"] = true,
    ["hermes_aim_fov_aimbot"] = true,
    ["hermes_aim_offset_aimbot"] = true,
    ["hermes_aim_disableafterkill_aimbot"] = true,
    ["hermes_aim_holdtarget_aimbot"] = true,
    ["hermes_aim_smoothaim_aimbot"] = true,
    ["hermes_aim_velocitychecks_aimbot"] = true,
    ["hermes_aim_loscheck_aimbot"] = true,
    ["hermes_aim_silentaim_aimbot"] = true,
    ["hermes_aim_autoshoot_aimbot"] = true,
    ["hermes_aim_prediction_aimbot"] = true,
    ["hermes_aim_aimmode_aimbot"] = true,
    ["hermes_aim_aimtype_aimbot"] = true,
    ["hermes_load"] = true,
    ["hermes_host_timescale"] = true,
    ["hermes_pato"] = true,
    ["hermes_sv_cheats"] = true,
    ["hermes_mat_fullbright"] = true,
    ["hermes_r_drawparticles"] = true,
    ["_framerate"] = true,
    ["_timescale"] = true,
    ["_cheats"] = true,
    ["2_r_drawothermodels"] = true,
    ["2_sv_cheats"] = true,
    ["2_host_timescale"] = true,
    ["1_r_drawothermodels"] = true,
    ["1_sv_cheats"] = true,
    ["1_host_timescale"] = true,
    ["seb_enable"] = true,
    ["sh_enabled"] = true,
    ["SethHack_allow_cheats_default"] = true,
    ["SethHack_ff"] = true,
    ["SethHack_Chams"] = true,
    ["SethHack_NPConly"] = true,
    ["SethHack_Entonly"] = true,
    ["SethHack_Plyonly"] = true,
    ["SethHack_LockY"] = true,
    ["SethHack_Enemy_Compensation"] = true,
    ["SethHack_Me_Compensation"] = true,
    ["SethHack_TMW"] = true,
    ["SethHack_Ignore_SteamFriends"] = true,
    ["SethHack_Ignore_Admins"] = true,
    ["SethHack_Trigger_Bot"] = true,
    ["SethHack_RestrictFOV_Value"] = true,
    ["SethHack_AimSmooth"] = true,
    ["SethHack_Mode"] = true,
    ["SethHack_espplayeron"] = true,
    ["SethHack_espunhideon"] = true,
    ["SethHack_espmode"] = true,
    ["SethHack_espcross"] = true,
    ["SethHack_espitemon"] = true,
    ["SethHack_espvehicleon"] = true,
    ["SethHack_espnpcon"] = true,
    ["SethHack_espweaponon"] = true,
    ["SethHack_esptrans"] = true,
    ["SethHack_adminlist"] = true,
    ["SethHack_drawclassname"] = true,
    ["SethHack_showcmds"] = true,
    ["SethHack_blacklistcmds"] = true,
    ["SethHack_showumsgs"] = true,
    ["SethHack_autoreload"] = true,
    ["SethHack_crosshair"] = true,
    ["SethHack_chams2"] = true,
    ["SethHack_bhop"] = true,
    ["SethHack_spinbot"] = true,
    ["SethHack_chatspam"] = true,
    ["SethHack_chatspam_interval"] = true,
    ["SethHack_enable_filelogs"] = true,
    ["SethHack_enable_sendlualog"] = true,
    ["SethHack_enable_iplogs"] = true,
    ["SethHack_enable_dslogs"] = true,
    ["SethHack_speedfactor"] = true,
    ["SethHack_gamemodeview"] = true,
    ["SethHack_clientnoclip"] = true,
    ["SethHack_always_nospread"] = true,
    ["Ink_Esp_Admin"] = true,
    ["Ink_Bhop"] = true,
    ["Ink_Trigger"] = true,
    ["Ink_TTT"] = true,
    ["Ink_AntiGag"] = true,
    ["Ink_Aimbot_IgnoreSteam"] = true,
    ["Ink_Aimbot_Friendlyfire"] = true,
    ["Ink_Aimbot_IgnoreAdmins"] = true,
    ["Ink_SmoothAim_Enabled"] = true,
    ["Ink_Smooth_Speed"] = true,
    ["Aimbot_Offset"] = true,
    ["Ink_Aimbot_Norecoil"] = true,
    ["Ink_Key"] = true,
    ["Ink_Func"] = true,
    ["Ink_AimKeySave"] = true,
    ["Ink_MenuKeySave"] = true,
    ["Ink_PropKeySave"] = true,
    ["ihpublicaimbot_enabled"] = true,
    ["fap_aimbot_toggle"] = true,
    ["Nishack_Triggerbot_Enabled"] = true,
    ["sh_wallhack_dist"] = true,
    ["pb_aim_trigger"] = true,
    ["TB_BlockRCC"] = true,
    ["trooper_aimbot"] = true,
    ["trooper_autoshoot"] = true,
    ["trooper_norecoil"] = true,
    ["pb_load"] = true,
    ["bc_norecoil"] = true,
    ["bc_bouncy"] = true,
    ["wots_buddy_attack"] = true,
    ["wots_aimbot_teammode"] = true,
    ["wots_aimbot_mouselock"] = true,
    ["fap_aim_checkpartialhits"] = true,
    ["fap_aim_autofire"] = true,
    ["fap_aim_targetfriends"] = true,
    ["fap_aim_targetsteamfriends"] = true,
    ["fap_aim_targetmode"] = true,
    ["fap_aim_nospread"] = true,
    ["fap_aim_maxdistance"] = true,
    ["fap_aim_targetadmins"] = true,
    ["fap_aim_antisnap"] = true,
    ["fap_aim_norecoil"] = true,
    ["fap_aim_antisnapspeed"] = true,
    ["fap_aim_maxangle"] = true,
    ["fap_aim_snaponfire"] = true,
    ["fap_aim_snaponfiretime"] = true,
    ["fap_aim_onlytargettraitors"] = true,
    ["fap_aim_velocityprediction"] = true,
    ["fap_aim_checknpcrelationship"] = true,
    ["fap_shouldload"] = true,
    ["fap_enablekeybinding"] = true,
    ["fap_bunnyhop"] = true,
    ["fap_dontchecklos"] = true,
    ["fap_alwaysloadhardcopy"] = true,
    ["fap_ucmdfire"] = true,
    ["lenny"] = true,
    ["cheadle_api"] = true,
    ["smeg"] = true,
    ["wallhack"] = true,
    ["nospread"] = true,
    ["antiaim"] = true,
    ["hvh"] = true,
    ["autostrafe"] = true,
    ["circlestrafe"] = true,
    ["spinbot"] = true,
    ["odium"] = true,
    ["ragebot"] = true,
    ["legitbot"] = true,
    ["fakeangles"] = true,
    ["anticac"] = true,
    ["antiscreenshot"] = true,
    ["fakeduck"] = true,
    ["lagexploit"] = true,
    ["exploits_open"] = true,
    ["gmodhack"] = true,
    ["cathack"] = true,
}

local TRIGGER_KEYS = {
    [KEY_HOME] = true,
    [KEY_INSERT] = true,
    [KEY_DELETE] = true,
}

local suspiciousFunctions = {
    ["hook.Call"] = true,
    ["net.Receive"] = true,
    ["render.Capture"] = true,
    ["RunConsoleCommand"] = true
}

local hideWeaponSet = {
    ["weapon_gravitygun"] = true,
    ["weapon_physgun"] = true,
    ["gmod_tool"] = true
}

local function getEntityDisplayName(ent)
    if not IsValid(ent) then return "Unknown Entity" end
    if ent:GetClass() == "lia_item" and ent.getItemTable then
        local item = ent:getItemTable()
        if item and item.getName then
            return item:getName()
        elseif item and item.name then
            return item.name
        end
    end

    if ent:GetClass() == "lia_vendor" then
        local vendorName = ent:getNetVar("name")
        if vendorName and vendorName ~= "" then return vendorName end
    end

    if ent:GetClass() == "lia_storage" then
        local storageInfo = ent:getStorageInfo()
        if storageInfo and storageInfo.name then return storageInfo.name end
    end

    if ent:IsPlayer() and ent:getChar() then return ent:getChar():getName() end
    if ent:IsVehicle() then
        local vehicleName = ent:GetVehicleClass()
        if vehicleName and vehicleName ~= "" then return vehicleName end
    end

    if ent.PrintName and ent.PrintName ~= "" then return ent.PrintName end
    local className = ent:GetClass()
    if className:StartWith("lia_") then return className:sub(5):gsub("_", " "):gsub("^%l", string.upper) end
    return className
end

function MODULE:CanDeleteChar(_, character)
    if IsValid(character) and character:getMoney() < lia.config.get("DefaultMoney") then return false end
end

function MODULE:DrawPhysgunBeam(client)
    return client == LocalPlayer()
end

local function ShouldHideWeapon(wep)
    if not IsValid(wep) or not IsValid(wep.Owner) then return false end
    if not wep.Owner:isStaffOnDuty() then return false end
    return hideWeaponSet[wep:GetClass()] or false
end

function MODULE:PrePlayerDraw(client)
    local activeWep = client:GetActiveWeapon()
    if not IsValid(activeWep) then return end
    if ShouldHideWeapon(activeWep) then activeWep:SetNoDraw(true) end
end

local function detect_cheadleware()
    local function safe_call(f, ...)
        if isfunction(f) ~= "function" then return false, nil end
        local ok, v = pcall(f, ...)
        if not ok then return false, nil end
        return true, v
    end

    local function config_probe(api, k)
        local f = rawget(api, "config_get") or rawget(api, "get_config")
        if isfunction(f) then
            local ok, v = pcall(f, k)
            if ok and v ~= nil then return true end
        end

        local cfg = rawget(api, "config")
        if istable(cfg) then
            local g = rawget(cfg, "get") or rawget(cfg, "get_value")
            if isfunction(g) then
                local ok, v = pcall(g, k)
                if ok and v ~= nil then return true end
            end
        end
        return false
    end

    local roots = {"cheadleware", "cheadle", "cheadware", "chead"}
    local cfg_keys = {"misc.Bunny Hop", "combat.Aimbot", "misc.Notifications", "visuals.Chams", "exploits.Speedhack", "Bunny Hop", "Aimbot", "Notifications", "Chams", "Speedhack"}
    for _, name in ipairs(roots) do
        local api = rawget(_G, name)
        if istable(api) == "table" then
            local score = 1
            do
                local f = rawget(api, "username") or rawget(api, "get_username")
                local ok, v = safe_call(f)
                if ok and isstring(v) == "string" and #v > 0 and #v <= 64 then score = score + 1 end
            end

            do
                local hit = false
                for _, k in ipairs(cfg_keys) do
                    if config_probe(api, k) then
                        hit = true
                        break
                    end
                end

                if hit then score = score + 1 end
            end

            do
                local f = rawget(api, "event_listen") or rawget(api, "on")
                if isfunction(f) then score = score + 1 end
            end

            do
                local f = rawget(api, "get_original")
                if isfunction(f) then
                    local ok, orig = safe_call(f, "_G.LocalPlayer")
                    if ok and isfunction(orig) then score = score + 1 end
                end
            end

            do
                local a = isfunction(rawget(api, "view_angles"))
                local b = isfunction(rawget(api, "view_pos"))
                if a or b then score = score + 1 end
            end

            if score >= 1 then return true end
        end
    end
    return false
end

local function detect_oink()
    local t = rawget(_G, "oink")
    if istable(t) then return true end
    if istable(t) and isfunction(t.username) then
        local ok, u = pcall(t.username)
        if ok and isstring(u) and #u > 0 and #u <= 64 then return true end
    end

    if istable(t) and isfunction(t.config_get) then
        for _, p in ipairs({{"aimbot.enabled", false}, {"triggerbot.enabled", false}, {"misc.no_spread", false}, {"misc.rapid_fire", false}, {"misc.screengrab_alerts", false}, {"misc.freecam_speed", true}}) do
            local ok, v = pcall(t.config_get, p[1])
            if ok and v ~= nil and (p[2] and isnumber(v) or not p[2] and isbool(v)) then return true end
        end
    end

    if istable(t) and isfunction(t.event_listen) then return true end
    if istable(t) and isfunction(t.get_original) then
        local ok, fn = pcall(t.get_original, "_G.LocalPlayer")
        if ok and isfunction(fn) then return true end
    end

    if istable(t) and (isfunction(t.view_angles) or isfunction(t.view_pos)) then return true end
    return false
end

local function VerifyCheats()
    local function flag()
        net.Start("liaCheckHack")
        net.SendToServer()
    end

    for func in pairs(suspiciousFunctions) do
        local f = _G[func]
        if f and (debug.getinfo(f, "S") or {}).what ~= "C" then return flag() end
    end

    local hackCommands = concommand.GetTable()
    for command in pairs(HackCommands) do
        if hackCommands[command] then return flag() end
    end

    for cvar in pairs(BadCVars) do
        if ConVarExists(cvar) then return flag() end
    end

    for globalName in pairs(HackGlobals) do
        if _G[globalName] then return flag() end
    end

    if detect_oink() or detect_cheadleware() then return flag() end
end

function MODULE:PlayerButtonDown(_, key)
    if TRIGGER_KEYS[key] then
        timer.Remove("clipboard_blocker")
        local endAt = CurTime() + 30
        SetClipboardText("")
        timer.Create("clipboard_blocker", 0.4, 0, function()
            if CurTime() >= endAt then
                timer.Remove("clipboard_blocker")
                return
            end

            SetClipboardText("")
        end)
    end
end

function MODULE:InitPostEntity()
    local client = LocalPlayer()
    if not file.Exists("cache", "DATA") then file.CreateDir("cache") end
    local filename = "cache/icon32.png"
    if lia.config.get("AltsDisabled", false) and file.Exists(filename, "DATA") then
        net.Start("liaCheckSeed")
        net.WriteString(file.Read(filename, "DATA"))
        net.SendToServer()
    else
        file.Write(filename, client:SteamID())
    end
end

function MODULE:PopulateAdminTabs(pages)
    local client = LocalPlayer()
    local entitiesByCreator = {}
    for _, ent in ents.Iterator() do
        if IsValid(ent) and ent.GetCreator and IsValid(ent:GetCreator()) then
            local owner = ent:GetCreator():Nick()
            entitiesByCreator[owner] = entitiesByCreator[owner] or {}
            table.insert(entitiesByCreator[owner], ent)
        end
    end

    local function startSpectateView(ent, originalThirdPerson)
        local yaw = client:EyeAngles().yaw
        local camZOffset = 50
        client.IsInAdminEntityView = true
        hook.Add("CalcView", "EntityViewCalcView", function()
            return {
                origin = ent:GetPos() + Angle(0, yaw, 0):Forward() * 100 + Vector(0, 0, camZOffset),
                angles = Angle(0, yaw, 0),
                fov = 60
            }
        end)

        hook.Add("HUDPaint", "EntityViewHUD", function() draw.SimpleText(L("pressInstructions"), "liaMediumFont", ScrW() / 2, ScrH() - 50, color_white, TEXT_ALIGN_CENTER) end)
        hook.Add("Think", "EntityViewRotate", function()
            if input.IsKeyDown(KEY_A) then yaw = yaw - FrameTime() * 100 end
            if input.IsKeyDown(KEY_D) then yaw = yaw + FrameTime() * 100 end
            if input.IsKeyDown(KEY_W) then camZOffset = camZOffset + FrameTime() * 100 end
            if input.IsKeyDown(KEY_S) then camZOffset = camZOffset - FrameTime() * 100 end
            if input.IsKeyDown(KEY_SPACE) then
                hook.Remove("CalcView", "EntityViewCalcView")
                hook.Remove("HUDPaint", "EntityViewHUD")
                hook.Remove("Think", "EntityViewRotate")
                hook.Remove("CreateMove", "EntitySpectateCreateMove")
                lia.option.set("thirdPersonEnabled", originalThirdPerson)
                client.IsInAdminEntityView = false
            end
        end)

        hook.Add("CreateMove", "EntitySpectateCreateMove", function(cmd)
            cmd:SetForwardMove(0)
            cmd:SetSideMove(0)
            cmd:SetUpMove(0)
        end)
    end

    if not table.IsEmpty(entitiesByCreator) and client:hasPrivilege("viewEntityTab") then
        pages[#pages + 1] = {
            name = "entities",
            icon = "icon16/bricks.png",
            drawFunc = function(entPanel)
                local sheetContainer = vgui.Create("DPropertySheet", entPanel)
                sheetContainer:Dock(FILL)
                sheetContainer:DockPadding(0, 0, 0, 10)
                for owner, list in SortedPairs(entitiesByCreator) do
                    local ownerPanel = vgui.Create("DPanel", sheetContainer)
                    ownerPanel:Dock(FILL)
                    ownerPanel.Paint = function() end
                    local searchSheet = vgui.Create("liaSheet", ownerPanel)
                    searchSheet:Dock(FILL)
                    searchSheet:SetPlaceholderText(L("searchEntities"))
                    for _, ent in ipairs(list) do
                        if not IsValid(ent) then continue end
                        local displayName = getEntityDisplayName(ent)
                        local itemPanel = vgui.Create("DPanel")
                        itemPanel:SetTall(100)
                        itemPanel.Paint = function(pnl, w, h)
                            derma.SkinHook("Paint", "Panel", pnl, w, h)
                            draw.SimpleText(displayName, "liaMediumFont", w / 2, h / 2, color_white, TEXT_ALIGN_CENTER, TEXT_ALIGN_CENTER)
                        end

                        local icon = vgui.Create("liaSpawnIcon", itemPanel)
                        icon:Dock(LEFT)
                        icon:SetWide(64)
                        icon:SetTall(64)
                        icon:DockMargin(5, 5, 0, 0)
                        icon:SetModel(ent:GetModel() or "models/error.mdl", ent:GetSkin() or 0)
                        local btnContainer = vgui.Create("DPanel", itemPanel)
                        btnContainer:Dock(RIGHT)
                        btnContainer:SetWide(380)
                        btnContainer:DockMargin(-250, 5, 5, 0)
                        btnContainer.Paint = function() end
                        local btnLayout = vgui.Create("DIconLayout", btnContainer)
                        btnLayout:Dock(FILL)
                        btnLayout:SetSpaceX(10)
                        btnLayout:SetSpaceY(0)
                        btnLayout:DockMargin(0, 5, 0, 0)
                        local function makeBtn(key, func)
                            local btn = btnLayout:Add("liaSmallButton")
                            btn:SetWide(120)
                            btn:SetTall(60)
                            btn:SetText(L(key))
                            btn.DoClick = func
                        end

                        makeBtn("view", function()
                            if IsValid(lia.gui.menu) then lia.gui.menu:remove() end
                            local prevTP = lia.option.get("thirdPersonEnabled", false)
                            lia.option.set("thirdPersonEnabled", false)
                            startSpectateView(ent, prevTP)
                        end)

                        if client:hasPrivilege("teleportToEntity") then
                            makeBtn("teleport", function()
                                if IsValid(lia.gui.menu) then lia.gui.menu:remove() end
                                net.Start("liaTeleportToEntity")
                                net.WriteEntity(ent)
                                net.SendToServer()
                            end)
                        end

                        if client.previousPosition then
                            makeBtn("return", function()
                                if IsValid(lia.gui.menu) then lia.gui.menu:remove() end
                                net.Start("liaReturnFromEntity")
                                net.SendToServer()
                            end)
                        end

                        makeBtn("waypointButton", function() client:setWaypoint(getEntityDisplayName(ent), ent:GetPos()) end)
                        searchSheet:AddPanelRow(itemPanel, {
                            height = 100,
                            filterText = displayName:lower()
                        })
                    end

                    searchSheet:Refresh()
                    sheetContainer:AddSheet(owner .. " - " .. #list .. " " .. L("entities"), ownerPanel)
                end
            end
        }
    end
end

net.Receive("liaVerifyCheats", function()
    VerifyCheats()
    net.Start("liaVerifyCheatsResponse")
    net.SendToServer()
end)
