--[[--

**Configuration Values:**.

- **AutomaticWeaponRegister**: Are Weapon Items Automatically Generated? | **bool**.

- **RegisterWeaponsBlackList**: What weapons shouldn't be generated by the automatic generator | **table**.

- **WeaponNameOverrides**: The name equivalents for a defined class. This should be used in case the system doesn't recognize a weapon's name | **table**.
]]
-- @configurations EasyWeapons
MODULE.name = "Utilities - Easy Weapons"
MODULE.author = "76561198312513285"
MODULE.discord = "@liliaplayer"
MODULE.desc = "Adds an Easy Way of Making Weapons."
