MODULE.name = "Compatibility - Advanced Dupe 2"
MODULE.author = "76561198312513285"
MODULE.discord = "@liliaplayer"
MODULE.desc = "Adds Advanced Dupe 2 Compatibility to Lilia."
MODULE.identifier = "AdvDupe2Compatibility"
