MODULE.name = "Recognition"
MODULE.author = "76561198312513285"
MODULE.discord = "@liliaplayer"
MODULE.version = "Stock"
MODULE.desc = "Adds the ability to recognize people / You can also allow auto faction recognition."