MODULE.name = "Map Scenes"
MODULE.author = "76561198312513285"
MODULE.discord = "@liliaplayer"
MODULE.version = "1.0"
MODULE.desc = "Adds areas of the map that are visible during character selection."
