--------------------------------------------------------------------------------------------------------
lia.config = lia.config or {}
--------------------------------------------------------------------------------------------------------
function GM:LoadConfigValues()
    lia.config = {
        CarRagdoll = true,
        HeadShotDamage = 2,
        TimeUntilDroppedSWEPRemoved = 15,
        PlayerSpawnVehicleDelay = 30,
        NPCsDropWeapons = true,
        DrawEntityShadows = true,
        WalkSpeed = 130,
        RunSpeed = 235,
        CharacterSwitchCooldownTimer = 5,
        CharacterSwitchCooldown = true,
        AutoRegen = false,
        HealingAmount = 10,
        HealingTimer = 60,
        PermaClass = true,
        MapCleanerEnabled = true,
        ItemCleanupTime = 7200,
        MapCleanupTime = 21600,
        DevServerIP = "45.61.170.66",
        DevServerPort = "27270",
        WalkRatio = 0.5,
        SalaryOverride = true,
        SalaryInterval = 300,
        TimeToEnterVehicle = 1,
        JumpCooldown = 0.8,
        MaxAttributes = 30,
        AllowExistNames = true,
        FactionBroadcastEnabled = true,
        AdvertisementEnabled = true,
        AdvertisementPrice = 25,
        DefaultGamemodeName = "Lilia - Skeleton",
        Color = Color(75, 119, 190),
        DarkTheme = true,
        Font = "Arial",
        GenericFont = "Segoe UI",
        WhitelistEnabled = false,
        MoneyModel = "models/props_lab/box01a.mdl",
        AutoWorkshopDownloader = false,
        MaxCharacters = 5,
        invW = 6,
        invH = 4,
        DefaultMoney = 0,
        CurrencyPluralName = "Dollars",
        CurrencySingularName = "Dollar",
        CurrencySymbol = "$",
        LoseWeapononDeathNPC = false,
        LoseWeapononDeathHuman = false,
        BranchWarning = true,
        VersionEnabled = true,
        version = "1.0",
        AllowVoice = true,
        CharAttrib = {"buttons/button16.wav", 30, 255},
        ThirdPersonEnabled = true,
        CrosshairEnabled = false,
        BarsDisabled = false,
        AmmoDrawEnabled = true,
        Vignette = true,
        CustomUIEnabled = true,
        TalkRanges = {
            ["Whispering"] = 120,
            ["Talking"] = 300,
            ["Yelling"] = 600,
        },
        EntitiesToBeRemoved = {
            ["env_fire"] = true,
            ["trigger_hurt"] = true,
            ["prop_ragdoll"] = true,
            ["prop_physics"] = true,
            ["spotlight_end"] = true,
            ["light"] = true,
            ["point_spotlight"] = true,
            ["beam"] = true,
            ["env_sprite"] = true,
            ["light_spot"] = true,
            ["func_tracktrain"] = true,
            ["point_template"] = true,
        },
        PlayerModelTposingFixer = {
            ["models/player/Group03/female_03.mdl"] = "citizen_female",
            ["models/player/Group01/male_02.mdl"] = "citizen_male",
        },
        DefaultStaff = {
            ["STEAMID"] = "RANK", 
        },
        PhysGunMoveRestrictedEntityList = {"prop_door_rotating", "lia_vendor"},
        RemoverBlockedEntities = {"lia_bodygroupcloset", "lia_vendor",},
        DuplicatorBlackList = {"lia_storage", "lia_money"},
        BlockedCollideEntities = {"lia_item", "lia_money"},
        RestrictedVehicles = {},
        UnLoadedPlugins = {
            ammosave = false,
            bodygrouper = false,
            chatbox = false,
            cmenu = false,
            corefiles = false,
            crashscreen = false,
            doors = false,
            f1menu = false,
            flashlight = false,
            gridinventory = false,
            interactionmenu = false,
            mainmenu = false,
            observer = false,
            pac = false,
            permakill = false,
            radio = false,
            raiseweapons = false,
            recognition = false,
            saveitems = false,
            scoreboard = false,
            serverblacklister = false,
            skills = false,
            spawnmenuitems = false,
            spawns = false,
            storage = false,
            tying = false,
            vendor = false,
            weaponselector = false,
            whitelist = false,
        },
    }

    hook.Run("InitializedConfig")
end
--------------------------------------------------------------------------------------------------------