GM.Name = "Lilia"
GM.version = "0.0.0"
GM.version = "0.0.0"
GM.version = "0.0.0"
GM.version = "0.0.0"
GM.version = "0.0.0"
GM.version = "0.0.0"
GM.Author = "Samael"
GM.Website = "https://discord.gg/esCRH5ckbQ"
include("core/loader.lua")
