--- Configuration for the Performance Module.
-- @configuration Performance

--- This table defines the default settings for the Performance Module.
-- @realm shared
-- @table Configuration
-- @field PlayerCountCarLimitEnabled Should Car Wipe be enabled? | **boolean**
-- @field PlayerCountCarLimit How many players are needed for cars to wipe | **integer**
-- @field tblAlwaysSend Entities that transmit States | **table**
-- @field RagdollCleaningTimer Time between Ragdolling Cleanups | **integer**
-- @field SoundsToMute What sounds should be muted | **table**
-- @field ItemLimit Maximum number of items and money entities on the map allowed before triggering cleanup | **integer**
-- @field CleanupDelay Time in seconds before removing items and money after reaching the threshold | **integer**
