local h = ScrH()

surface.CreateFont("TBCWarmUpFont", {
    font = "Arial",
    extended = false,
    size = 20 * h / 500,
    weight = 500,
    blursize = 0,
    scanlines = 0,
    antialias = true,
    underline = false,
    italic = false,
    strikeout = false,
    symbol = false,
    rotary = false,
    shadow = false,
    additive = false,
    outline = true,
})

surface.CreateFont("TBCSmallFont", {
    font = "Arial",
    extended = false,
    size = 14 * h / 500,
    weight = 500,
    blursize = 0,
    scanlines = 0,
    antialias = true,
    underline = false,
    italic = false,
    strikeout = false,
    symbol = false,
    rotary = false,
    shadow = false,
    additive = false,
    outline = true,
})

surface.CreateFont("TBCTinyFont", {
    font = "Arial",
    extended = false,
    size = 7 * h / 500,
    weight = 500,
    blursize = 0,
    scanlines = 0,
    antialias = true,
    underline = false,
    italic = false,
    strikeout = false,
    symbol = false,
    rotary = false,
    shadow = false,
    additive = false,
    outline = true,
})