MODULE.name = "Utilities - Persistance"
MODULE.author = "76561198312513285"
MODULE.discord = "@liliaplayer"
MODULE.desc = "Adds a Module that implements persistance"
MODULE.identifier = "PersistanceCore"