--- Configuration for Protection Module.
-- @configuration Protection

--- This table defines the default settings for the Protection Module.
-- @realm shared
-- @table Configuration
-- @field CarRagdoll Determines whether being hit by a car results in ragdolling | **bool**
-- @field OnDamageCharacterSwitchCooldown Specifies whether cooldown on character switching is enabled after taking damage | **bool**
-- @field OnDamageCharacterSwitchCooldownTimer Sets the cooldown duration (in seconds) on character switching after taking damage | **integer**
-- @field SwitchCooldownOnAllEntities Specifies whether damage cooldown applies to all entities or just humans. If false, it applies only to humans | **bool**
-- @field CharacterSwitchCooldown Indicates whether a cooldown for character switching exists | **bool**
-- @field CharacterSwitchCooldownTimer Sets the duration (in seconds) of the character switch cooldown | **integer**
-- @field NPCsDropWeapons Controls whether NPCs drop weapons upon death | **bool**
-- @field TimeUntilDroppedSWEPRemoved Specifies the duration (in seconds) until a dropped SWEP is removed. This pertains to actual SWEPs, not weapon items | **integer**
-- @field BlockedCollideEntities Lists entities with collisions disabled | **table**
-- @field KnownExploits Lists known exploits that the protection module is aware of | **table**
-- @field HackCommands Lists commands available in the hack menu | **table**
-- @field HackGlobals Lists global variables accessible in the hack menu | **table**
-- @field BadCVars Lists undesirable console variables that should be monitored or blocked | **table**
-- @field ExploitableNetMessages Lists exploitable Net Messages that should be monitored or blocked | **table**
-- @field ActExploitTimer Specifies the duration (in seconds) a player remains unable to deal damage after using an "act" command | **integer**
-- @field DefaultNets Lists the default net messages that do not get logged | **table**
-- @field AltsDisabled Whether or not alting is permitted | **bool**