--- Configuration for F1Menu Module.
-- @configuration F1Menu

--- This table defines the default settings for the F1Menu Module.
-- @realm shared
-- @table Configuration
-- @field KickOnEnteringMainMenu Set Music Volume on Main Menu | **boolean**
-- @field F1ThirdPersonEnabled Set Music Volume on Main Menu | **boolean**
-- @field F1DisplayModel Set Music Volume on Main Menu | **boolean**
-- @field RulesEnabled Set Music Volume on Main Menu | **boolean**
-- @field TutorialEnabled Set Music Volume on Main Menu | **boolean**
-- @field FAQEnabled Set Music Volume on Main Menu | **boolean**
-- @field InfoMenuLocation What corner does your Information appear on (TopLeft, TopRight, BottomRight, BottomCenter)| **string**
-- @field FAQQuestions Set Music Volume on Main Menu | **table**
