--- Configuration for the F1Menu Module.
-- @configuration F1Menu

--- This table defines the default settings for the F1Menu Module.
-- @realm shared
-- @table Configuration
-- @field F1ThirdPersonEnabled Set Music Volume on Main Menu | **boolean**
-- @field RulesEnabled Set Music Volume on Main Menu | **boolean**
-- @field TutorialEnabled Set Music Volume on Main Menu | **boolean**
-- @field FAQEnabled Set Music Volume on Main Menu | **boolean**
-- @field FAQQuestions Set Music Volume on Main Menu | **table**
