--- Configuration for Easy Weapons Module.
-- @configuration EasyWeapons

--- This table defines the default settings for the EasyWeapons Module.
-- @realm shared
-- @table Configuration
-- @field AutomaticWeaponRegister Are Weapon Items Automatically Generated? | **boolean**
-- @field NotifyWeaponRegister Whether or not the weapon generations are printed in console | **boolean**
-- @field RegisterWeaponsBlackList What weapons shouldn't be generated by the automatic generator | **table**
-- @field WeaponOverrides A table containing custom properties for specific weapon classes. This should be used when you want to override a weapon's stat. | **table**
