--- Configuration for Easy Weapons Module.
-- @configurations EasyWeapons

--- This table defines the default settings for the EasyWeapons Module.
-- @realm shared
-- @table Configuration
-- @field AutomaticWeaponRegister Are Weapon Items Automatically Generated? | **bool**
-- @field NotifyWeaponRegister Whether or not the weapon generations are printed in console | **bool**
-- @field RegisterWeaponsBlackList What weapons shouldn't be generated by the automatic generator | **table**
-- @field WeaponNameOverrides The name equivalents for a defined class. This should be used in case the system doesn't recognize a weapon's name | **table**
