--- Configuration for HUD Module.
-- @configuration HUD

--- This table defines the default settings for the HUD Module.
-- @realm shared
-- @table Configuration
-- @field Vignette Enable Vignette Effect | **boolean**
-- @field BranchWarning Activate Branch Warning | **boolean**
-- @field CrosshairEnabled Enable Crosshair | **boolean**
-- @field BarsDisabled Disable Bars | **boolean**
-- @field NoDrawCrosshairWeapon Weapons with No Crosshair | **table**
-- @field AmmoDrawEnabled Enable Ammo Draw | **boolean**
-- @field HiddenHUDElements Disabled Sandbox HUD Elements | **table**
