--- Configuration for the HUD Module.
-- @configuration HUD

--- This table defines the default settings for the HUD module.
-- @realm shared
-- @table Configuration
-- @field Vignette Enables the vignette effect | **boolean**
-- @field BranchWarning Activates branch warnings | **boolean**
-- @field CrosshairEnabled Enables the crosshair | **boolean**
-- @field BarsDisabled Disables bars | **boolean**
-- @field NoDrawCrosshairWeapon Weapons without a crosshair | **table**
-- @field AmmoDrawEnabled Enables ammo display | **boolean**
-- @field HiddenHUDElements Disables sandbox HUD elements | **table**
-- @field WatermarkLogo The path to the watermark image (PNG) | **string**
-- @field GamemodeVersion The version of the gamemode | **string**