--- Configuration for HUD Module.
-- @configurationmodule HUD

--- This table defines the default settings for the HUD Module.
-- @realm shared
-- @table Configuration
-- @field Vignette Enable Vignette Effect | **bool**
-- @field BranchWarning Activate Branch Warning | **bool**
-- @field CrosshairEnabled Enable Crosshair | **bool**
-- @field BarsDisabled Disable Bars | **bool**
-- @field NoDrawCrosshairWeapon Weapons with No Crosshair | **table**
-- @field AmmoDrawEnabled Enable Ammo Draw | **bool**
-- @field DarkTheme Toggle Dark Theme | **bool**
-- @field HiddenHUDElements Disabled Sandbox HUD Elements | **table**
