MODULE.DrowningEnabled = true
MODULE.DamageScalerEnabled = true
MODULE.HurtSoundEnabled = true
MODULE.DeathSoundEnabled = true
MODULE.LimbDamage = 0.5
MODULE.DamageScale = 1
MODULE.HeadShotDamage = 2
MODULE.DrownTime = 30
MODULE.DrownDamage = 10
MODULE.LimbHitgroups = {HITGROUP_GEAR, HITGROUP_RIGHTARM, HITGROUP_LEFTARM}
