RunConsoleCommand("arccw_override_hud_off", "1")
RunConsoleCommand("arccw_override_crosshair_off", 1)
RunConsoleCommand("arccw_mult_defaultammo", 0)
RunConsoleCommand("arccw_enable_dropping", 0)
RunConsoleCommand("arccw_attinv_free", 0)
RunConsoleCommand("arccw_attinv_loseondie", 0)
RunConsoleCommand("arccw_malfunction", 2)
RunConsoleCommand("arccw_npc_atts", 0)