--- Configuration for the Doors Module.
-- @configuration Doors
--- This table defines the default settings for the Doors Module.
-- @realm shared
-- @table Configuration
-- @field DoorSellRatio Percentage you can sell a door for | **number**
-- @field DoorLockTime Time it takes to lock a door | **number**
-- @field DoorsStartDisabled Indicates whether doors start disabled | **boolean**
