MODULE.TimeUntilDroppedSWEPRemoved = 15
MODULE.NPCsDropWeapons = false
MODULE.CharacterSwitchCooldownTimer = 5
MODULE.CharacterSwitchCooldown = true
MODULE.OnDamageCharacterSwitchCooldownTimer = 15
MODULE.OnDamageCharacterSwitchCooldown = true
MODULE.CarRagdoll = true
MODULE.BlockedCollideEntities = {"lia_item", "lia_money"}
MODULE.SwitchCooldownOnAllEntities = true
MODULE.DuplicatorBlackList = {"lia_storage", "lia_money"}
MODULE.CanNotPermaProp = {"lia_vendor", "lia_bodygrouper"}