MODULE.MusicVolume = 0.25
MODULE.Music = ""
MODULE.BackgroundURL = ""
MODULE.CenterLogo = ""
MODULE.ButtonLogo = ""
MODULE.ButtonURL = ""
MODULE.CharMenuBGInputDisabled = true
MODULE.CanSelectBodygroups = true
MODULE.CanSelectSkins = true
MODULE.CharHover = {"buttons/button15.wav", 35, 250}
MODULE.CharClick = {"buttons/button14.wav", 35, 255}
MODULE.CharWarning = {"friends/friend_join.wav", 40, 255}
MODULE.KickOnEnteringMainMenu = true