MODULE.name = "Compatibility - Prone Mod"
MODULE.author = "76561198312513285"
MODULE.discord = "@liliaplayer"
MODULE.desc = "Adds Compatibility to Prone Mod"
MODULE.identifier = "ProneModCompatibility"