MODULE.name = "Recognition"
MODULE.author = "Samael"
MODULE.discord = "@liliaplayer"
MODULE.version = "1.0"
MODULE.desc = "Adds the ability to recognize people / You can also allow auto faction recognition."
