MODULE.RestrictedEnts = {"func_button", "class C_BaseEntity", "func_brush", "func_tracktrain", "func_door", "func_door_rotating", "prop_static", "prop_physics_override", "prop_dynamic", "func_movelinear", "prop_door_rotating", "lia_vendor"}
MODULE.RemoverBlockedEntities = {"lia_bodygroupcloset", "lia_vendor",}
MODULE.DuplicatorBlackList = {"lia_storage", "lia_money"}
MODULE.RestrictedVehicles = {}
MODULE.BlackListedProps = {}
MODULE.CanNotPermaProp = {"lia_vendor", "lia_bodygrouper"}
MODULE.ButtonList = {"models/maxofs2d/button_01.mdl", "models/maxofs2d/button_02.mdl", "models/maxofs2d/button_03.mdl", "models/maxofs2d/button_04.mdl", "models/maxofs2d/button_05.mdl", "models/maxofs2d/button_06.mdl", "models/maxofs2d/button_slider.mdl"}
MODULE.PassableOnFreeze = false
MODULE.PlayerSpawnVehicleDelay = 30
MODULE.ToolInterval = 0.5
