--- Configuration for Recognition Module.
-- @configuration Recognition

--- This table defines the default settings for the Recognition Module.
-- @realm shared
-- @table Configuration
-- @field RecognitionEnabled Is character recognition enabled? | **boolean**
-- @field FactionAutoRecognize Do members from the same faction always auto-recognize each other? | **boolean**
-- @field FakeNamesEnabled Are fake names enabled? | **boolean**
-- @field ScoreboardHiddenVars Variables to hide from a non-recognized character in the scoreboard | **table**
-- @field ChatIsRecognized Chat types that are recognized | **table**
-- @field MemberToMemberAutoRecognition Factions that auto-recognize members between each other | **table**
