MODULE.Vignette = true
MODULE.BranchWarning = true
MODULE.CrosshairEnabled = false
MODULE.BarsDisabled = false
MODULE.AmmoDrawEnabled = true
MODULE.WatermarkEnabled = false
MODULE.WatermarkLogo = ""
MODULE.GamemodeVersion = ""
MODULE.NoDrawCrosshairWeapon = {"weapon_crowbar", "weapon_stunstick", "weapon_bugbait"}
MODULE.HiddenHUDElements = {"CHUDAutoAim", "CHudHealth", "CHudCrosshair", "CHudVoiceStatus", "CHudBattery", "CHudAmmo", "CHudSecondaryAmmo", "CHudHistoryResource",}