--- Configuration for the Attributes Module.
-- @configuration Attributes

--- This table defines the default settings for the Attributes Module.
-- @realm shared
-- @table Configuration
-- @field StaminaBlur Is Stamina Blur Enabled? | **boolean**
-- @field StaminaSlowdown Is Stamina Slowdown Enabled? | **boolean**
-- @field DefaultStamina Sets Default Stamina Value | **number**
-- @field StaminaBlurThreshold Sets Stamina Threshold for Blur to Show | **number**
-- @field StaminaBreathingThreshold Sets Stamina Threshold for Breathing to Happen | **number**
-- @field CharAttrib Sets Sounds Made when hitting the attribute button | **table**
