MODULE.name = "administrationModuleName"
MODULE.author = "Samael"
MODULE.discord = "@liliaplayer"
MODULE.desc = "administrationToolsDescription"
MODULE.Privileges = {
    {
        Name = "canUseItemSpawner",
        ID = "canUseItemSpawner",
        MinAccess = "admin",
        Category = "categoryStaffItems",
    },
    {
        Name = "managePropBlacklist",
        ID = "managePropBlacklist",
        MinAccess = "superadmin",
        Category = "categoryBlacklisting",
    },
    {
        Name = "manageVehicleBlacklist",
        ID = "manageVehicleBlacklist",
        MinAccess = "superadmin",
        Category = "categoryBlacklisting",
    },
    {
        Name = "accessEditConfigurationMenu",
        ID = "accessEditConfigurationMenu",
        MinAccess = "superadmin",
        Category = "userInterface",
    },
    {
        Name = "manageUsergroups",
        ID = "manageUsergroups",
        MinAccess = "superadmin",
        Category = "categoryUsergroups",
    },
    {
        Name = "viewStaffManagement",
        ID = "viewStaffManagement",
        MinAccess = "superadmin",
        Category = "categoryStaffManagement",
    },
    {
        Name = "canAccessPlayerList",
        ID = "canAccessPlayerList",
        MinAccess = "admin",
        Category = "players",
    },
    {
        Name = "listCharacters",
        ID = "listCharacters",
        MinAccess = "admin",
        Category = "character",
    },
    {
        Name = "canAccessFlagManagement",
        ID = "canAccessFlagManagement",
        MinAccess = "superadmin",
        Category = "flags",
    },
    {
        ID = "createStaffCharacter",
        Name = "createStaffCharacter",
        MinAccess = "admin",
        Category = "categoryStaffManagement",
    },
    {
        ID = "canBypassSAMFactionWhitelist",
        Name = "canBypassSAMFactionWhitelist",
        MinAccess = "superadmin",
        Category = "categorySAM",
    },
    {
        ID = "canEditSimfphysCars",
        Name = "canEditSimfphysCars",
        MinAccess = "superadmin",
        Category = "simfphysVehicles",
    },
    {
        ID = "canSeeSAMNotificationsOutsideStaff",
        Name = "canSeeSAMNotificationsOutsideStaff",
        MinAccess = "superadmin",
        Category = "categorySAM",
    },
    {
        ID = "checkInventories",
        Name = "checkInventories",
        MinAccess = "admin",
        Category = "categoryStaffManagement",
    },
    {
        ID = "manageAttributes",
        Name = "manageAttributes",
        MinAccess = "admin",
        Category = "categoryStaffManagement",
    },
    {
        ID = "manageCharacterInformation",
        Name = "manageCharacterInformation",
        MinAccess = "admin",
        Category = "categoryStaffManagement",
    },
    {
        ID = "manageCharacters",
        Name = "manageCharacters",
        MinAccess = "admin",
        Category = "categoryStaffManagement",
    },
    {
        ID = "manageClasses",
        Name = "manageClasses",
        MinAccess = "admin",
        Category = "categoryStaffManagement",
    },
    {
        ID = "manageDoors",
        Name = "manageDoors",
        MinAccess = "admin",
        Category = "categoryStaffManagement",
    },
    {
        ID = "manageFlags",
        Name = "manageFlags",
        MinAccess = "admin",
        Category = "categoryStaffManagement",
    },
    {
        ID = "manageSitRooms",
        Name = "manageSitRooms",
        MinAccess = "admin",
        Category = "categoryStaffManagement",
    },
    {
        ID = "manageTransfers",
        Name = "manageTransfers",
        MinAccess = "admin",
        Category = "categoryStaffManagement",
    },
    {
        ID = "receiveCheaterNotifications",
        Name = "receiveCheaterNotifications",
        MinAccess = "admin",
        Category = "exploiting",
    },
    {
        ID = "stopSoundForEveryone",
        Name = "stopSoundForEveryone",
        MinAccess = "superadmin",
        Category = "categoryServer",
    },
    {
        ID = "useDisallowedTools",
        Name = "useDisallowedTools",
        MinAccess = "superadmin",
        Category = "categoryStaffTools",
    },
    {
        ID = "viewPlayerWarnings",
        Name = "viewPlayerWarnings",
        MinAccess = "admin",
        Category = "warning",
    },
    {
        Name = "canRemoveWarns",
        ID = "canRemoveWarns",
        MinAccess = "superadmin",
        Category = "warning",
    },
    {
        Name = "alwaysSeeTickets",
        ID = "alwaysSeeTickets",
        MinAccess = "superadmin",
        Category = "tickets",
    },
    {
        Name = "canBypassCharacterLock",
        ID = "canBypassCharacterLock",
        MinAccess = "superadmin",
        Category = "categoryStaffManagement",
    },
    {
        Name = "canGrabWorldProps",
        ID = "canGrabWorldProps",
        MinAccess = "superadmin",
        Category = "categoryStaffPhysgun",
    },
    {
        Name = "canGrabPlayers",
        ID = "canGrabPlayers",
        MinAccess = "superadmin",
        Category = "categoryStaffPhysgun",
    },
    {
        Name = "physgunPickup",
        ID = "physgunPickup",
        MinAccess = "admin",
        Category = "categoryStaffPhysgun",
    },
    {
        Name = "canAccessItemInformations",
        ID = "canAccessItemInformations",
        MinAccess = "superadmin",
        Category = "categoryStaffItems",
    },
    {
        Name = "physgunPickupRestrictedEntities",
        ID = "physgunPickupRestrictedEntities",
        MinAccess = "superadmin",
        Category = "categoryStaffPhysgun",
    },
    {
        Name = "physgunPickupVehicles",
        ID = "physgunPickupVehicles",
        MinAccess = "admin",
        Category = "categoryStaffPhysgun",
    },
    {
        Name = "cantBeGrabbedPhysgun",
        ID = "cantBeGrabbedPhysgun",
        MinAccess = "superadmin",
        Category = "categoryStaffProtection",
    },
    {
        Name = "canPhysgunReload",
        ID = "canPhysgunReload",
        MinAccess = "superadmin",
        Category = "categoryStaffPhysgun",
    },
    {
        Name = "noClipOutsideStaff",
        ID = "noClipOutsideStaff",
        MinAccess = "superadmin",
        Category = "categoryStaffMovement",
    },
    {
        Name = "noClipESPOffsetStaff",
        ID = "noClipESPOffsetStaff",
        MinAccess = "superadmin",
        Category = "userInterface",
    },
    {
        Name = "canPropertyWorldEntities",
        ID = "canPropertyWorldEntities",
        MinAccess = "superadmin",
        Category = "categoryStaffManagement",
    },
    {
        Name = "canSpawnRagdolls",
        ID = "canSpawnRagdolls",
        MinAccess = "admin",
        Category = "spawnPermissions",
    },
    {
        Name = "canSpawnSWEPs",
        ID = "canSpawnSWEPs",
        MinAccess = "superadmin",
        Category = "spawnPermissions",
    },
    {
        Name = "canEditWeapons",
        ID = "canEditWeapons",
        MinAccess = "superadmin",
        Category = "spawnPermissions",
    },
    {
        Name = "canSpawnEffects",
        ID = "canSpawnEffects",
        MinAccess = "admin",
        Category = "spawnPermissions",
    },
    {
        Name = "canSpawnProps",
        ID = "canSpawnProps",
        MinAccess = "admin",
        Category = "spawnPermissions",
    },
    {
        Name = "canSpawnBlacklistedProps",
        ID = "canSpawnBlacklistedProps",
        MinAccess = "superadmin",
        Category = "spawnPermissions",
    },
    {
        Name = "canSpawnNPCs",
        ID = "canSpawnNPCs",
        MinAccess = "superadmin",
        Category = "spawnPermissions",
    },
    {
        Name = "noCarSpawnDelay",
        ID = "noCarSpawnDelay",
        MinAccess = "superadmin",
        Category = "spawnPermissions",
    },
    {
        Name = "canSpawnCars",
        ID = "canSpawnCars",
        MinAccess = "admin",
        Category = "spawnPermissions",
    },
    {
        Name = "canSpawnBlacklistedCars",
        ID = "canSpawnBlacklistedCars",
        MinAccess = "superadmin",
        Category = "spawnPermissions",
    },
    {
        Name = "canSpawnSENTs",
        ID = "canSpawnSENTs",
        MinAccess = "admin",
        Category = "spawnPermissions",
    },
    {
        Name = "canRemoveBlockedEntities",
        ID = "canRemoveBlockedEntities",
        MinAccess = "admin",
        Category = "categoryStaffBlacklisting",
    },
    {
        Name = "canRemoveWorldEntities",
        ID = "canRemoveWorldEntities",
        MinAccess = "superadmin",
        Category = "categoryStaffManagement",
    },
    {
        Name = "canSeeLogs",
        ID = "canSeeLogs",
        MinAccess = "superadmin",
        Category = "categoryLogging",
    },
    {
        Name = "alwaysSpawnAdminStick",
        ID = "alwaysSpawnAdminStick",
        MinAccess = "superadmin",
        Category = "adminStick",
    },
    {
        Name = "commandBan",
        ID = "command_ban",
        MinAccess = "admin",
        Category = "commands",
    },
    {
        Name = "commandKick",
        ID = "command_kick",
        MinAccess = "admin",
        Category = "commands",
    },
    {
        Name = "commandKill",
        ID = "command_kill",
        MinAccess = "admin",
        Category = "commands",
    },
    {
        Name = "commandFreeze",
        ID = "command_freeze",
        MinAccess = "admin",
        Category = "commands",
    },
    {
        Name = "commandUnfreeze",
        ID = "command_unfreeze",
        MinAccess = "admin",
        Category = "commands",
    },
    {
        Name = "commandSlay",
        ID = "command_slay",
        MinAccess = "admin",
        Category = "commands",
    },
    {
        Name = "commandRespawn",
        ID = "command_respawn",
        MinAccess = "admin",
        Category = "commands",
    },
    {
        Name = "commandBlind",
        ID = "command_blind",
        MinAccess = "admin",
        Category = "commands",
    },
    {
        Name = "commandUnblind",
        ID = "command_unblind",
        MinAccess = "admin",
        Category = "commands",
    },
    {
        Name = "commandGag",
        ID = "command_gag",
        MinAccess = "admin",
        Category = "commands",
    },
    {
        Name = "commandUngag",
        ID = "command_ungag",
        MinAccess = "admin",
        Category = "commands",
    },
    {
        Name = "commandMute",
        ID = "command_mute",
        MinAccess = "admin",
        Category = "commands",
    },
    {
        Name = "commandUnmute",
        ID = "command_unmute",
        MinAccess = "admin",
        Category = "commands",
    },
    {
        Name = "commandBring",
        ID = "command_bring",
        MinAccess = "admin",
        Category = "commands",
    },
    {
        Name = "commandGoto",
        ID = "command_goto",
        MinAccess = "admin",
        Category = "commands",
    },
    {
        Name = "commandReturn",
        ID = "command_return",
        MinAccess = "admin",
        Category = "commands",
    },
    {
        Name = "commandJail",
        ID = "command_jail",
        MinAccess = "admin",
        Category = "commands",
    },
    {
        Name = "commandUnjail",
        ID = "command_unjail",
        MinAccess = "admin",
        Category = "commands",
    },
    {
        Name = "commandCloak",
        ID = "command_cloak",
        MinAccess = "admin",
        Category = "commands",
    },
    {
        Name = "commandUncloak",
        ID = "command_uncloak",
        MinAccess = "admin",
        Category = "commands",
    },
    {
        Name = "commandGod",
        ID = "command_god",
        MinAccess = "admin",
        Category = "commands",
    },
    {
        Name = "commandUngod",
        ID = "command_ungod",
        MinAccess = "admin",
        Category = "commands",
    },
    {
        Name = "commandIgnite",
        ID = "command_ignite",
        MinAccess = "admin",
        Category = "commands",
    },
    {
        Name = "commandExtinguish",
        ID = "command_extinguish",
        MinAccess = "admin",
        Category = "commands",
    },
    {
        Name = "commandStrip",
        ID = "command_strip",
        MinAccess = "admin",
        Category = "commands",
    },
    {
        Name = "canManageNPCs",
        ID = "canManageNPCs",
        MinAccess = "admin",
        Category = "NPCs",
    },
    {
        Name = "canManageProperties",
        ID = "canManageProperties",
        MinAccess = "superadmin",
        Category = "categoryStaffManagement",
    },
    {
        Name = "seeInsertNotifications",
        ID = "seeInsertNotifications",
        MinAccess = "superadmin",
        Category = "categoryStaffManagement",
    },
}
