MODULE.name = "administrationModuleName"
MODULE.author = "Samael"
MODULE.discord = "@liliaplayer"
MODULE.desc = "administrationToolsDescription"
MODULE.Privileges = {
    {
        Name = "canUseItemSpawner",
        ID = "canUseItemSpawner",
        MinAccess = "admin",
        Category = "categoryStaffItems",
    },
    {
        Name = "managePropBlacklist",
        ID = "managePropBlacklist",
        MinAccess = "superadmin",
        Category = "categoryBlacklisting",
    },
    {
        Name = "manageVehicleBlacklist",
        ID = "manageVehicleBlacklist",
        MinAccess = "superadmin",
        Category = "categoryBlacklisting",
    },
    {
        Name = "accessEditConfigurationMenu",
        ID = "accessEditConfigurationMenu",
        MinAccess = "superadmin",
        Category = "categoryConfiguration",
    },
    {
        Name = "manageUsergroups",
        ID = "manageUsergroups",
        MinAccess = "superadmin",
        Category = "categoryUsergroups",
    },
    {
        Name = "viewStaffManagement",
        ID = "viewStaffManagement",
        MinAccess = "superadmin",
        Category = "categoryStaffManagement",
    },
    {
        Name = "canAccessPlayerList",
        ID = "canAccessPlayerList",
        MinAccess = "admin",
        Category = "players",
    },
    {
        Name = "listCharacters",
        ID = "listCharacters",
        MinAccess = "admin",
        Category = "character",
    },
    {
        Name = "canAccessFlagManagement",
        ID = "canAccessFlagManagement",
        MinAccess = "superadmin",
        Category = "flags",
    },
    {
        ID = "createStaffCharacter",
        Name = "createStaffCharacter",
        MinAccess = "admin",
        Category = "categoryStaffManagement",
    },
    {
        ID = "canBypassSAMFactionWhitelist",
        Name = "canBypassSAMFactionWhitelist",
        MinAccess = "superadmin",
        Category = "categorySAM",
    },
    {
        ID = "canEditSimfphysCars",
        Name = "canEditSimfphysCars",
        MinAccess = "superadmin",
        Category = "simfphysVehicles",
    },
    {
        ID = "canSeeSAMNotificationsOutsideStaff",
        Name = "canSeeSAMNotificationsOutsideStaff",
        MinAccess = "superadmin",
        Category = "categorySAM",
    },
    {
        ID = "checkInventories",
        Name = "checkInventories",
        MinAccess = "admin",
        Category = "categoryStaffManagement",
    },
    {
        ID = "manageAttributes",
        Name = "manageAttributes",
        MinAccess = "admin",
        Category = "categoryStaffManagement",
    },
    {
        ID = "manageCharacterInformation",
        Name = "manageCharacterInformation",
        MinAccess = "admin",
        Category = "categoryStaffManagement",
    },
    {
        ID = "manageCharacters",
        Name = "manageCharacters",
        MinAccess = "admin",
        Category = "categoryStaffManagement",
    },
    {
        ID = "manageClasses",
        Name = "manageClasses",
        MinAccess = "admin",
        Category = "categoryStaffManagement",
    },
    {
        ID = "manageDoors",
        Name = "manageDoors",
        MinAccess = "admin",
        Category = "categoryStaffManagement",
    },
    {
        ID = "manageFlags",
        Name = "manageFlags",
        MinAccess = "admin",
        Category = "categoryStaffManagement",
    },
    {
        ID = "manageSitRooms",
        Name = "manageSitRooms",
        MinAccess = "admin",
        Category = "categoryStaffManagement",
    },
    {
        ID = "manageTransfers",
        Name = "manageTransfers",
        MinAccess = "admin",
        Category = "categoryStaffManagement",
    },
    {
        ID = "receiveCheaterNotifications",
        Name = "receiveCheaterNotifications",
        MinAccess = "admin",
        Category = "protection",
    },
    {
        ID = "stopSoundForEveryone",
        Name = "stopSoundForEveryone",
        MinAccess = "superadmin",
        Category = "categoryServer",
    },
    {
        ID = "useDisallowedTools",
        Name = "useDisallowedTools",
        MinAccess = "superadmin",
        Category = "categoryStaffTools",
    },
    {
        ID = "viewPlayerWarnings",
        Name = "viewPlayerWarnings",
        MinAccess = "admin",
        Category = "warning",
    },
    {
        Name = "canRemoveWarns",
        ID = "canRemoveWarns",
        MinAccess = "superadmin",
        Category = "warning",
    },
    {
        Name = "alwaysSeeTickets",
        ID = "alwaysSeeTickets",
        MinAccess = "superadmin",
        Category = "tickets",
    },
    {
        Name = "canBypassCharacterLock",
        ID = "canBypassCharacterLock",
        MinAccess = "superadmin",
        Category = "categoryStaffManagement",
    },
    {
        Name = "canGrabWorldProps",
        ID = "canGrabWorldProps",
        MinAccess = "superadmin",
        Category = "categoryStaffPhysgun",
    },
    {
        Name = "canGrabPlayers",
        ID = "canGrabPlayers",
        MinAccess = "superadmin",
        Category = "categoryStaffPhysgun",
    },
    {
        Name = "physgunPickup",
        ID = "physgunPickup",
        MinAccess = "admin",
        Category = "categoryStaffPhysgun",
    },
    {
        Name = "canAccessItemInformations",
        ID = "canAccessItemInformations",
        MinAccess = "superadmin",
        Category = "categoryStaffItems",
    },
    {
        Name = "physgunPickupRestrictedEntities",
        ID = "physgunPickupRestrictedEntities",
        MinAccess = "superadmin",
        Category = "categoryStaffPhysgun",
    },
    {
        Name = "physgunPickupVehicles",
        ID = "physgunPickupVehicles",
        MinAccess = "admin",
        Category = "categoryStaffPhysgun",
    },
    {
        Name = "cantBeGrabbedPhysgun",
        ID = "cantBeGrabbedPhysgun",
        MinAccess = "superadmin",
        Category = "categoryStaffProtection",
    },
    {
        Name = "canPhysgunReload",
        ID = "canPhysgunReload",
        MinAccess = "superadmin",
        Category = "categoryStaffPhysgun",
    },
    {
        Name = "noClipOutsideStaff",
        ID = "noClipOutsideStaff",
        MinAccess = "superadmin",
        Category = "categoryStaffMovement",
    },
    {
        Name = "noClipESPOffsetStaff",
        ID = "noClipESPOffsetStaff",
        MinAccess = "superadmin",
        Category = "categoryStaffSettings",
    },
    {
        Name = "canPropertyWorldEntities",
        ID = "canPropertyWorldEntities",
        MinAccess = "superadmin",
        Category = "categoryStaffManagement",
    },
    {
        Name = "canSpawnRagdolls",
        ID = "canSpawnRagdolls",
        MinAccess = "admin",
        Category = "categorySpawnRagdolls",
    },
    {
        Name = "canSpawnSWEPs",
        ID = "canSpawnSWEPs",
        MinAccess = "superadmin",
        Category = "categorySpawnSWEPs",
    },
    {
        Name = "canSpawnEffects",
        ID = "canSpawnEffects",
        MinAccess = "admin",
        Category = "categorySpawnEffects",
    },
    {
        Name = "canSpawnProps",
        ID = "canSpawnProps",
        MinAccess = "admin",
        Category = "categorySpawnProps",
    },
    {
        Name = "canSpawnBlacklistedProps",
        ID = "canSpawnBlacklistedProps",
        MinAccess = "superadmin",
        Category = "categorySpawnBlacklisting",
    },
    {
        Name = "canSpawnNPCs",
        ID = "canSpawnNPCs",
        MinAccess = "superadmin",
        Category = "categorySpawnNPCs",
    },
    {
        Name = "noCarSpawnDelay",
        ID = "noCarSpawnDelay",
        MinAccess = "superadmin",
        Category = "categorySpawnVehicles",
    },
    {
        Name = "canSpawnCars",
        ID = "canSpawnCars",
        MinAccess = "admin",
        Category = "categorySpawnVehicles",
    },
    {
        Name = "canSpawnBlacklistedCars",
        ID = "canSpawnBlacklistedCars",
        MinAccess = "superadmin",
        Category = "categorySpawnBlacklisting",
    },
    {
        Name = "canSpawnSENTs",
        ID = "canSpawnSENTs",
        MinAccess = "admin",
        Category = "categorySpawnSENTs",
    },
    {
        Name = "canRemoveBlockedEntities",
        ID = "canRemoveBlockedEntities",
        MinAccess = "admin",
        Category = "categoryStaffBlacklisting",
    },
    {
        Name = "canRemoveWorldEntities",
        ID = "canRemoveWorldEntities",
        MinAccess = "superadmin",
        Category = "categoryStaffManagement",
    },
    {
        Name = "canSeeLogs",
        ID = "canSeeLogs",
        MinAccess = "superadmin",
        Category = "categoryLogging",
    },
    {
        Name = "alwaysSpawnAdminStick",
        ID = "alwaysSpawnAdminStick",
        MinAccess = "superadmin",
        Category = "adminStick",
    },
}