MODULE.name = "3D Voice"
MODULE.author = "76561198312513285"
MODULE.discord = "@liliaplayer"
MODULE.version = "Stock"
MODULE.desc = "Adds a Voice Tone Based Voice Module"
MODULE.identifier = "VoiceCore"