MODULE.name = "Bodygrouper"
MODULE.author = "76561198312513285"
MODULE.discord = "@liliaplayer"
MODULE.version = "Stock"
MODULE.desc = "Adds a bodygroup menu and bodygroup closet, akin to BodygroupR on GModStore"
