lia.includeDir("lilia/libraries/thirdparty", true, true)
lia.include("lilia/libraries/database/hooks/server.lua")
lia.include("lilia/meta/database.lua", "shared")
lia.include("lilia/libraries/database/concommands/server.lua")
lia.include("lilia/libraries/util/shared.lua")
lia.include("lilia/libraries/util/client.lua")
lia.include("lilia/libraries/util/server.lua")
lia.include("lilia/meta/character.lua", "shared")
lia.include("lilia/libraries/character/shared.lua")
lia.include("lilia/libraries/animations/shared.lua")
lia.include("lilia/libraries/animations/config/shared.lua")
lia.include("lilia/libraries/hooks/shared.lua")
lia.include("lilia/libraries/hooks/client.lua")
lia.include("lilia/libraries/hooks/server.lua")
lia.include("lilia/libraries/character/server.lua")
lia.include("lilia/libraries/chatbox.lua", "shared")
lia.include("lilia/libraries/commands.lua", "shared")
lia.include("lilia/libraries/flags.lua", "shared")
lia.include("lilia/libraries/inventory/shared.lua")
lia.include("lilia/libraries/inventory/client.lua")
lia.include("lilia/libraries/inventory/server.lua")
lia.include("lilia/libraries/items/shared.lua")
lia.include("lilia/libraries/items/config/server.lua")
lia.include("lilia/libraries/languages.lua", "shared")
lia.include("lilia/libraries/networking/shared.lua")
lia.include("lilia/libraries/networking/client.lua")
lia.include("lilia/libraries/networking/server.lua")
lia.include("lilia/libraries/attributes.lua", "shared")
lia.include("lilia/libraries/factions.lua", "shared")
lia.include("lilia/libraries/classes.lua", "shared")
lia.include("lilia/libraries/currency/shared.lua")
lia.include("lilia/libraries/currency/hooks/server.lua")
lia.include("lilia/libraries/date.lua", "shared")
lia.include("lilia/libraries/module.lua", "shared")
lia.include("lilia/meta/inventory.lua", "shared")
lia.include("lilia/meta/item.lua", "shared")
lia.include("lilia/libraries/items/hooks/client.lua")
lia.include("lilia/libraries/items/hooks/server.lua")
lia.include("lilia/meta/entity.lua", "shared")
lia.include("lilia/meta/player.lua", "shared")
lia.include("lilia/commands/client.lua")
lia.include("lilia/commands/server.lua")
lia.include("lilia/netcalls/client.lua")
lia.include("lilia/netcalls/server.lua")
lia.include("lilia/libraries/logger/shared.lua")
lia.include("lilia/libraries/concommands/shared.lua")
lia.include("lilia/libraries/concommands/server.lua")
lia.include("lilia/libraries/concommands/client.lua")
lia.include("lilia/libraries/color.lua", "client")
lia.include("lilia/libraries/menu.lua", "client")
lia.include("lilia/libraries/notice.lua", "client")
lia.include("lilia/libraries/bars.lua", "client")
lia.include("lilia/libraries/animations/hooks/shared.lua")
lia.include("lilia/libraries/logger/client.lua")
lia.include("lilia/libraries/logger/server.lua")
lia.item.loadFromDir("lilia/libraries/items/config/items", true)
lia.lang.loadFromDir("lilia/languages")
lia.util.loadEntities("lilia/libraries/currency/entities")
lia.util.loadEntities("lilia/libraries/items/entities")
lia.util.loadEntities("lilia/libraries/entities")
