MODULE.name = "Interaction Menu"
MODULE.author = "76561198312513285"
MODULE.discord = "@liliaplayer"
MODULE.version = "1.0"
MODULE.desc = "Adds Several Shortcuts to a menu."
MODULE.identifier = "PIM"
