MODULE.name = "modulePermissionsName"
MODULE.author = "Samael"
MODULE.discord = "@liliaplayer"
MODULE.desc = "modulePermissionsDesc"
MODULE.Privileges = {
    {
        Name = L("canBypassCharacterLock"),
        ID = "canBypassCharacterLock",
        MinAccess = "superadmin",
        Category = "categoryStaffManagement",
    },
    {
        Name = L("canGrabWorldProps"),
        ID = "canGrabWorldProps",
        MinAccess = "superadmin",
        Category = "categoryStaffPhysgun",
    },
    {
        Name = L("canGrabPlayers"),
        ID = "canGrabPlayers",
        MinAccess = "superadmin",
        Category = "categoryStaffPhysgun",
    },
    {
        Name = L("physgunPickup"),
        ID = "physgunPickup",
        MinAccess = "admin",
        Category = "categoryStaffPhysgun",
    },
    {
        Name = L("canAccessItemInformations"),
        ID = "canAccessItemInformations",
        MinAccess = "superadmin",
        Category = "categoryStaffItems",
    },
    {
        Name = L("physgunPickupRestrictedEntities"),
        ID = "physgunPickupRestrictedEntities",
        MinAccess = "superadmin",
        Category = "categoryStaffPhysgun",
    },
    {
        Name = L("physgunPickupVehicles"),
        ID = "physgunPickupVehicles",
        MinAccess = "admin",
        Category = "categoryStaffPhysgun",
    },
    {
        Name = L("cantBeGrabbedPhysgun"),
        ID = "cantBeGrabbedPhysgun",
        MinAccess = "superadmin",
        Category = "categoryStaffProtection",
    },
    {
        Name = L("canPhysgunReload"),
        ID = "canPhysgunReload",
        MinAccess = "superadmin",
        Category = "categoryStaffPhysgun",
    },
    {
        Name = L("noClipOutsideStaff"),
        ID = "noClipOutsideStaff",
        MinAccess = "superadmin",
        Category = "categoryStaffMovement",
    },
    {
        Name = L("noClipESPOffsetStaff"),
        ID = "noClipESPOffsetStaff",
        MinAccess = "superadmin",
        Category = "categoryStaffSettings",
    },
    {
        Name = L("canPropertyWorldEntities"),
        ID = "canPropertyWorldEntities",
        MinAccess = "superadmin",
        Category = "categoryStaffManagement",
    },
    {
        Name = L("manageVehicleBlacklist"),
        ID = "manageVehicleBlacklist",
        MinAccess = "superadmin",
        Category = "categoryStaffBlacklisting",
    },
    {
        Name = L("manageEntityBlacklist"),
        ID = "manageEntityBlacklist",
        MinAccess = "superadmin",
        Category = "categoryStaffBlacklisting",
    },
    {
        Name = L("canSpawnRagdolls"),
        ID = "canSpawnRagdolls",
        MinAccess = "admin",
        Category = "categorySpawnRagdolls",
    },
    {
        Name = L("canSpawnSWEPs"),
        ID = "canSpawnSWEPs",
        MinAccess = "superadmin",
        Category = "categorySpawnSWEPs",
    },
    {
        Name = L("canSpawnEffects"),
        ID = "canSpawnEffects",
        MinAccess = "admin",
        Category = "categorySpawnEffects",
    },
    {
        Name = L("canSpawnProps"),
        ID = "canSpawnProps",
        MinAccess = "admin",
        Category = "categorySpawnProps",
    },
    {
        Name = L("canSpawnBlacklistedProps"),
        ID = "canSpawnBlacklistedProps",
        MinAccess = "superadmin",
        Category = "categorySpawnBlacklisting",
    },
    {
        Name = L("canSpawnNPCs"),
        ID = "canSpawnNPCs",
        MinAccess = "superadmin",
        Category = "categorySpawnNPCs",
    },
    {
        Name = L("noCarSpawnDelay"),
        ID = "noCarSpawnDelay",
        MinAccess = "superadmin",
        Category = "categorySpawnVehicles",
    },
    {
        Name = L("noSpawnDelay"),
        ID = "noSpawnDelay",
        MinAccess = "admin",
        Category = "categorySpawnGeneral",
    },
    {
        Name = L("canSpawnCars"),
        ID = "canSpawnCars",
        MinAccess = "admin",
        Category = "categorySpawnVehicles",
    },
    {
        Name = L("canSpawnBlacklistedCars"),
        ID = "canSpawnBlacklistedCars",
        MinAccess = "superadmin",
        Category = "categorySpawnBlacklisting",
    },
    {
        Name = L("canSpawnSENTs"),
        ID = "canSpawnSENTs",
        MinAccess = "admin",
        Category = "categorySpawnSENTs",
    },
    {
        Name = L("usergroupStaff"),
        ID = "usergroupStaff",
        MinAccess = "admin",
        Category = "categoryStaffUsergroups",
    },
    {
        Name = L("usergroupVIP"),
        ID = "usergroupVIP",
        MinAccess = "superadmin",
        Category = "categoryStaffUsergroups",
    },
    {
        Name = L("listEntities"),
        ID = "listEntities",
        MinAccess = "superadmin",
        Category = "categoryStaffTools",
    },
    {
        Name = L("canRemoveBlockedEntities"),
        ID = "canRemoveBlockedEntities",
        MinAccess = "admin",
        Category = "categoryStaffBlacklisting",
    },
    {
        Name = L("canRemoveWorldEntities"),
        ID = "canRemoveWorldEntities",
        MinAccess = "superadmin",
        Category = "categoryStaffManagement",
    },
}