local PLUGIN = PLUGIN
PLUGIN.name = "Doors Saver"
PLUGIN.author = "Leonheart#7476/Taxin2012"
PLUGIN.desc = "Saves purchased by players doors."
PLUGIN.DOORS_BUFFER = PLUGIN.DOORS_BUFFER or {}
PLUGIN.DOORS_ACCESS_BUFFER = PLUGIN.DOORS_ACCESS_BUFFER or {}
PLUGIN.DOORS_TITLES_BUFFER = PLUGIN.DOORS_TITLES_BUFFER or {}