ENT.Type = "anim"
ENT.Base = "lia_npc"
ENT.PrintName = "Node Dialog NPC"
ENT.Author = "Samael"
ENT.Contact = "@liliaplayer"
ENT.Category = "Lilia"
ENT.Spawnable = true
ENT.AdminOnly = false
ENT.DrawEntityInfo = true
ENT.IsPersistent = true
ENT.NodeGeneratedDialog = true
