name: "gmod-upload"
description: "Packs a Garry's Mod addon to a .gma file and uploads to the Steam workshop"

branding:
  icon: box
  color: gray-dark

inputs:
  changelog:
    description: "Changelog"
    required: false
    default: ""
  id:
    description: "Workshop item id"
    required: true
  config:
    description: "Path of addon.json, or json file to treat as such."
    required: false
    default: "addon.json"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@master

    - name: Download SteamCMD
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install lib32gcc-s1
        mkdir ~/Steam
        curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf - -C ~/Steam

    - name: Download Lua 5.3
      shell: bash
      run: |
        sudo apt-get install lua5.3

    - name: Run gma packer
      shell: bash
      run: |
        lua5.3 ${{ github.action_path }}/gma.lua ${{ inputs.id }}.gma ${{ inputs.config }}

    - name: Create .vdf file
      shell: bash
      run: |
        cat <<"EOF" | sed 's/"/\x27/g; s/`/\\`/g; s/\$/\\$/g' > changelog.txt
         ${{ inputs.changelog }}
        EOF
        cat > workshop.vdf <<EOF
          "workshopitem" {
            "appid" "4000"
            "publishedfileid" "${{ inputs.id }}"
            "contentfolder" "`pwd`/${{ inputs.id }}.gma"
            "changenote" "$(cat changelog.txt)"
          }
        EOF

    - name: Run SteamCMD
      shell: bash
      run: |
        ~/Steam/steamcmd.sh +login $STEAM_USERNAME $STEAM_PASSWORD +workshop_build_item `pwd -P`/workshop.vdf +quit

    - name: Print Errors
      if: failure()
      shell: bash
      run: |
        echo ~/Steam/logs/stderr.txt
        echo "$(cat ~/Steam/logs/stderr.txt)"
        echo
        echo ~/Steam/logs/workshop_log.txt
        echo "$(cat ~/Steam/logs/workshop_log.txt)"
        echo
        echo ~/Steam/workshopbuilds/depot_build_4000.log
        echo "$(cat ~/Steam/workshopbuilds/depot_build_4000.log)"
        echo
        echo workshop.vdf
        echo "$(cat `pwd -P`/workshop.vdf)"

        exit 1