CONFIG.SchemaYear = 2023
CONFIG.contentURL = "https://discord.gg/HmfaJ9brfz"
CONFIG.PKActive = false
CONFIG.PKWorld = false
CONFIG.MoneyModel = "models/props_lab/box01a.mdl"
CONFIG.StaminaSlowdown = true
--///////////////////////////
CONFIG.RespawnButton = true
CONFIG.AFKKickEnabled = true
CONFIG.AllowVoice = true
CONFIG.CarRagdoll = true
CONFIG.CharacterSwitchCooldown = true
CONFIG.PlayerSprayEnabled = true
CONFIG.FlashlightEnabled = true
CONFIG.FlashlightItemNeeded = false
CONFIG.CentsCompatibility = true
CONFIG.StormFox2Compatibility = true
CONFIG.StormFox2Seasons = true
CONFIG.StormFox2TimePerSeason = true
CONFIG.WepAlwaysRaised = true
CONFIG.WeaponToggleDelay = 1
CONFIG.WeaponRaiseTimer = 1
CONFIG.DefaultStamina = 100
CONFIG.IntroEnabled = false
CONFIG.AlwaysPlayIntro = false
CONFIG.introFont = "Cambria"
CONFIG.ServerVersionDisplayerEnabled = true
CONFIG.VoiceDistance = 600
CONFIG.AFKTime = 300
CONFIG.Year = tonumber(os.date("%Y"))
CONFIG.Month = tonumber(os.date("%m"))
CONFIG.Day = tonumber(os.date("%d"))
CONFIG.StaminaBlur = false
CONFIG.CrosshairEnabled = false
CONFIG.DrawEntityShadows = true
CONFIG.Vignette = true
CONFIG.BarsDisabled = false
CONFIG.AmmoDrawEnabled = true
CONFIG.DarkTheme = true
CONFIG.Color = Color(75, 119, 190)
CONFIG.Font = "Arial"
CONFIG.GenericFont = "Segoe UI"
CONFIG.ChatSizeDiff = false
CONFIG.MaxChars = 5
CONFIG.SpawnTime = 5
CONFIG.invW = 6
CONFIG.invH = 4
CONFIG.MinDescLen = 16
CONFIG.WalkSpeed = 130
CONFIG.RunSpeed = 235
CONFIG.WalkRatio = 0.5
CONFIG.PunchStamina = 10
CONFIG.DefMoney = 0
CONFIG.SaveInterval = 300
CONFIG.SaveInterval = 300
CONFIG.StaffAutoRecognize = false
CONFIG.FactionAutoRecognize = false
CONFIG.AllowExistNames = false
CONFIG.StrMultiplier = false
CONFIG.CustomChatSound = ""
CONFIG.F1MenuLaunchUnanchor = "buttons/lightswitch2.wav"
CONFIG.MenuButtonRollover = "ui/buttonrollover.wav"
CONFIG.SoundMenuButtonPressed = "ui/buttonclickrelease.wav"
CONFIG.Notify = {"garrysmod/content_downloaded.wav", 50, 250}
CONFIG.CharHover = {"buttons/button15.wav", 35, 250}
CONFIG.CharClick = {"buttons/button14.wav", 35, 255}
CONFIG.CharWarning = {"friends/friend_join.wav", 40, 255}
CONFIG.CharAttrib = {"buttons/button16.wav", 30, 255}
CONFIG.VendorClick = {"buttons/button15.wav", 30, 250}
--///////////////////////////