MODULE.name = "Compatibility - Advanced Dupe 1"
MODULE.author = "76561198312513285"
MODULE.discord = "@liliaplayer"
MODULE.desc = "Adds Advanced Dupe 1 Compatibility to Lilia."
MODULE.identifier = "AdvDupeCompatibility"
