--- Configuration for the Permissions Module.
-- @configuration Permissions
--- This table defines the default settings for the Permissions Module.
-- @realm shared
-- @table Configuration
-- @field NoClipESPEntities Entities highlighted by NoClip ESP | **table**
-- @field SpawnMenuLimit Determines if the spawn menu is limited to PET flag holders or staff | **boolean**
-- @field ESPColors Colors used for different entity types in ESP | **table**
