MODULE.TimeUntilDroppedSWEPRemoved = 15
MODULE.NPCsDropWeapons = false
MODULE.CharacterSwitchCooldownTimer = 5
MODULE.CharacterSwitchCooldown = true
MODULE.OnDamageCharacterSwitchCooldownTimer = 15
MODULE.OnDamageCharacterSwitchCooldown = true
MODULE.CarRagdoll = true
MODULE.BlockedCollideEntities = {"lia_item", "lia_money"}
MODULE.SwitchCooldownOnAllEntities = true
MODULE.DuplicatorBlackList = {"lia_storage", "lia_money"}
MODULE.CanNotPermaProp = {"lia_vendor", "lia_bodygrouper"}
MODULE.AltsDisabled = false
MODULE.PassableOnFreeze = false
MODULE.RemoverBlockedEntities = {"lia_bodygroupcloset", "lia_vendor",}
MODULE.BlackListedProps = {}
MODULE.RestrictedEnts = {"func_button", "class C_BaseEntity", "func_brush", "func_tracktrain", "func_door", "func_door_rotating", "prop_static", "prop_physics_override", "prop_dynamic", "func_movelinear", "prop_door_rotating", "lia_vendor"}
MODULE.RestrictedVehicles = {}
MODULE.PlayerSpawnVehicleDelay = 30
MODULE.DisableLuaRun = true
