--- Configuration for RealisticDamage Module.
-- @configuration RealisticDamage

--- This table defines the default settings for the RealisticDamage Module.
-- @realm shared
-- @table Configuration
-- @field DrowningEnabled Indicates whether drowning is enabled | **boolean**
-- @field DamageScalerEnabled Indicates whether damage scaling is enabled | **boolean**
-- @field HurtSoundEnabled Indicates whether hurt sounds are enabled | **boolean**
-- @field DeathSoundEnabled Indicates whether death sounds are enabled | **boolean**
-- @field LimbDamage Damage multiplier for limb hits | **number**
-- @field DamageScale Global damage scale multiplier | **number**
-- @field HeadShotDamage Damage multiplier for headshots | **number**
-- @field DrownTime Time (in seconds) it takes for a character to drown | **integer**
-- @field DrownDamage Amount of damage dealt per second while drowning | **integer**
-- @field LimbHitgroups Hitgroups considered as limbs | **table**
-- @field MaleDeathSounds Sounds played when a male character dies | **table**
-- @field MaleHurtSounds Sounds played when a male character is hurt | **table**
-- @field FemaleDeathSounds Sounds played when a female character dies | **table**
-- @field FemaleHurtSounds Sounds played when a female character is hurt | **table**
-- @field DrownSounds Sounds played when a character is drowning | **table**
-- @field InjuriesTable Defines the text referring to condition that appears when analyzing someone's health | **table**
